//! CUDA C++ lowering — the one backend-specific module (v1).
//!
//! Everything CUDA-shaped (the vector types, `__global__`, the
//! `blockIdx`/`blockDim` launch indexing, the fp16/bf16 headers) lives here. The
//! math itself is lowered by the language-neutral [`crate::backend::lower_expr`]
//! — and reused verbatim across dtypes, because CUDA overloads `+ - * /` for
//! `__half` / `__nv_bfloat16` the same as for `float`.

use crate::backend::{lower_expr, Backend, GeneratedKernel, Lowering};
use crate::ir::{Access, BinaryOp, ReduceOp, ScalarExpr, UnaryOp};
use crate::plan::{rr_role, KernelPlan, RrRole, Schedule};
use baracuda_kernels_types::{Contiguity, ElementKind, OperandKey};

/// The CUDA C++ backend. Lowers a [`KernelPlan`] to `.cu` source.
#[derive(Copy, Clone, Debug, Default)]
pub struct Cuda;

impl Backend for Cuda {
    fn name(&self) -> &str {
        "cuda"
    }

    fn supports_dtype(&self, dtype: ElementKind) -> bool {
        scalar_ctype(dtype).is_some()
    }

    fn lower(&self, plan: &KernelPlan<'_>) -> GeneratedKernel {
        let Some(ctype) = scalar_ctype(plan.dtype) else {
            panic!("cuda backend: unsupported dtype {:?}", plan.dtype);
        };
        assert!(
            params_used(plan.body).is_empty()
                || matches!(plan.dtype, ElementKind::F32 | ElementKind::F32Strict),
            "cuda backend v1: scalar params are f32-only for now (dtype {:?})",
            plan.dtype
        );
        match plan.schedule {
            Schedule::Vectorized { width } => match vector_type(plan.dtype, width) {
                Some((vty, lanes)) => emit_vectorized(plan, vty, lanes),
                // dtype has no packed vector path yet (e.g. f16 V8): fall back to
                // scalar — still correct, and still gets the narrower-dtype
                // bandwidth win.
                None => emit_scalar(plan, ctype),
            },
            Schedule::Scalar => emit_scalar(plan, ctype),
            Schedule::Strided => emit_strided(plan, ctype),
            Schedule::Reduction { op } => emit_reduction(plan, ctype, op),
            Schedule::RowReduce { .. } => emit_row_reduce(plan, ctype),
        }
    }
}

/// CUDA scalar type for a dtype, or `None` if the backend can't lower it yet.
fn scalar_ctype(dt: ElementKind) -> Option<&'static str> {
    Some(match dt {
        ElementKind::F32 | ElementKind::F32Strict => "float",
        ElementKind::F64 => "double",
        ElementKind::F16 => "__half",
        ElementKind::Bf16 => "__nv_bfloat16",
        ElementKind::I32 => "int",
        ElementKind::I64 => "long long",
        _ => return None,
    })
}

/// Extra header a dtype needs (fp16 / bf16 device operators), if any.
fn extra_include(dt: ElementKind) -> Option<&'static str> {
    match dt {
        ElementKind::F16 => Some("#include <cuda_fp16.h>\n"),
        ElementKind::Bf16 => Some("#include <cuda_bf16.h>\n"),
        _ => None,
    }
}

/// Vector type + lane names for a `(dtype, width)` the backend can vectorize, or
/// `None` to fall back to scalar. f16/bf16 packed vectorization (`half2`
/// intrinsics) is a follow-up.
fn vector_type(dt: ElementKind, width: u32) -> Option<(&'static str, &'static [&'static str])> {
    match (dt, width) {
        (ElementKind::F32 | ElementKind::F32Strict, 4) => Some(("float4", &["x", "y", "z", "w"])),
        (ElementKind::F32 | ElementKind::F32Strict, 2) => Some(("float2", &["x", "y"])),
        (ElementKind::F64, 2) => Some(("double2", &["x", "y"])),
        _ => None,
    }
}

/// Short dtype tag for generated symbol names. Only called for dtypes that pass
/// [`scalar_ctype`].
fn dtype_tag(dt: ElementKind) -> &'static str {
    match dt {
        ElementKind::F32 => "f32",
        ElementKind::F32Strict => "f32s",
        ElementKind::F64 => "f64",
        ElementKind::F16 => "f16",
        ElementKind::Bf16 => "bf16",
        ElementKind::I32 => "i32",
        ElementKind::I64 => "i64",
        _ => "x",
    }
}

fn header(plan: &KernelPlan<'_>, name: &str) -> String {
    // Header-light, portable device source: no `<cstdint>` / `<cuda_runtime.h>`,
    // so the SAME source compiles under both nvcc (AOT) and nvrtc (JIT). Device
    // built-ins (`threadIdx`, `float4`, `__global__`) are implicit in both; the
    // 64-bit index type is the built-in `long long`. Only the fp16/bf16 operator
    // headers are included (nvrtc bundles them), and only when the dtype needs them.
    let mut h = format!(
        "// Generated by baracuda-kernelgen — do not edit.\n\
         // op: {} | cell: {}\n",
        plan.op_name,
        plan.key.to_token(),
    );
    if let Some(inc) = extra_include(plan.dtype) {
        h.push_str(inc);
    }
    h.push('\n');
    h.push_str(&format!("extern \"C\" __global__ void {name}(\n"));
    h
}

fn emit_vectorized(plan: &KernelPlan<'_>, vty: &str, lanes: &[&str]) -> GeneratedKernel {
    let name = format!(
        "baracuda_gen_{}_{}_co_v{}",
        plan.op_name,
        dtype_tag(plan.dtype),
        lanes.len()
    );
    let n = plan.n_inputs;
    let mut s = header(plan, &name);
    for i in 0..n {
        s.push_str(&format!("    const {vty}* __restrict__ in{i},\n"));
    }
    s.push_str(&format!("    {vty}* __restrict__ out,\n"));
    s.push_str(&format!("    long long nv{})\n{{\n", param_args(plan.body)));
    s.push_str("    long long i = (long long)blockIdx.x * blockDim.x + threadIdx.x;\n");
    s.push_str("    long long step = (long long)gridDim.x * blockDim.x;\n");
    s.push_str("    for (; i < nv; i += step) {\n");
    for i in 0..n {
        s.push_str(&format!("        {vty} v{i} = in{i}[i];\n"));
    }
    s.push_str(&format!("        {vty} vo;\n"));
    for lane in lanes {
        let acc = |idx: u8| format!("v{idx}.{lane}");
        s.push_str(&format!("        vo.{lane} = {};\n", lower_expr(
            plan.body,
            &Lowering {
                leaf: &acc,
                reduced: &|i| unreachable!("no Reduced leaf outside RowReduce: red{i}"),
                unary: &|op, x| cuda_unary(op, x, plan.dtype),
                binary: &|op, a, b| cuda_binary(op, a, b, plan.dtype),
            },
        )));
    }
    s.push_str("        out[i] = vo;\n    }\n}\n");
    GeneratedKernel { name, source: s }
}

fn emit_scalar(plan: &KernelPlan<'_>, ctype: &str) -> GeneratedKernel {
    let name = format!("baracuda_gen_{}_{}_scalar", plan.op_name, dtype_tag(plan.dtype));
    let n = plan.n_inputs;
    let mut s = header(plan, &name);
    for i in 0..n {
        s.push_str(&format!("    const {ctype}* __restrict__ in{i},\n"));
    }
    s.push_str(&format!("    {ctype}* __restrict__ out,\n"));
    s.push_str(&format!("    long long n{})\n{{\n", param_args(plan.body)));
    s.push_str("    long long i = (long long)blockIdx.x * blockDim.x + threadIdx.x;\n");
    s.push_str("    long long step = (long long)gridDim.x * blockDim.x;\n");
    let acc = |idx: u8| format!("in{idx}[i]");
    s.push_str(&format!(
        "    for (; i < n; i += step) out[i] = {};\n",
        lower_expr(
            plan.body,
            &Lowering {
                leaf: &acc,
                reduced: &|i| unreachable!("no Reduced leaf outside RowReduce: red{i}"),
                unary: &|op, x| cuda_unary(op, x, plan.dtype),
                binary: &|op, a, b| cuda_binary(op, a, b, plan.dtype),
            },
        )
    ));
    s.push_str("}\n");
    GeneratedKernel { name, source: s }
}

fn emit_strided(plan: &KernelPlan<'_>, ctype: &str) -> GeneratedKernel {
    let rank = plan.key.rank as usize;
    let n = plan.n_inputs as usize;
    let name = format!(
        "baracuda_gen_{}_{}_strided_r{}",
        plan.op_name,
        dtype_tag(plan.dtype),
        rank
    );
    let mut s = header(plan, &name);
    for i in 0..n {
        s.push_str(&format!("    const {ctype}* __restrict__ in{i},\n"));
    }
    s.push_str(&format!("    {ctype}* __restrict__ out,\n"));
    s.push_str("    const long long* __restrict__ shape,\n");
    for i in 0..n {
        s.push_str(&format!("    const long long* __restrict__ s{i},\n"));
    }
    s.push_str("    const long long* __restrict__ so,\n");
    s.push_str(&format!("    long long n{})\n{{\n", param_args(plan.body)));
    // Hoist fully-broadcast inputs: their offset is loop-invariant, load once.
    for k in 0..n {
        if is_fully_broadcast(plan.key.operands[k], rank) {
            s.push_str(&format!("    {ctype} h{k} = in{k}[0];\n"));
        }
    }
    s.push_str("    long long i = (long long)blockIdx.x * blockDim.x + threadIdx.x;\n");
    s.push_str("    long long step = (long long)gridDim.x * blockDim.x;\n");
    s.push_str("    for (; i < n; i += step) {\n");
    s.push_str("        long long lin = i;\n");
    // Row-major unravel (last axis fastest), unrolled over the iteration rank.
    for d in (0..rank).rev() {
        s.push_str(&format!(
            "        long long c{d} = lin % shape[{d}]; lin /= shape[{d}];\n"
        ));
    }
    for k in 0..n {
        if !is_fully_broadcast(plan.key.operands[k], rank) {
            let off = offset_expr(plan.key.operands[k], &format!("s{k}"), rank);
            s.push_str(&format!("        long long o{k} = {off};\n"));
        }
    }
    let oo = offset_expr(plan.key.operands[n], "so", rank);
    s.push_str(&format!("        long long oo = {oo};\n"));
    let acc = |idx: u8| {
        if is_fully_broadcast(plan.key.operands[idx as usize], rank) {
            format!("h{idx}")
        } else {
            format!("in{idx}[o{idx}]")
        }
    };
    s.push_str(&format!("        out[oo] = {};\n", lower_expr(
            plan.body,
            &Lowering {
                leaf: &acc,
                reduced: &|i| unreachable!("no Reduced leaf outside RowReduce: red{i}"),
                unary: &|op, x| cuda_unary(op, x, plan.dtype),
                binary: &|op, a, b| cuda_binary(op, a, b, plan.dtype),
            },
        )));
    s.push_str("    }\n}\n");
    GeneratedKernel { name, source: s }
}

/// Emit a **last-axis reduction**: one thread per output element, a sequential
/// fold over the contiguous trailing axis (`k` elements). The accumulator is
/// `float` — `double` for f64 and f32-strict (the strict mode wants a wide fold)
/// — so f16/bf16/f32 inputs fold up-converted: more precise than folding in the
/// narrow type, and it avoids the missing `__half2` reductions. The body computes
/// the per-element pre-reduction expression; `Sum`/`Mean` fold from a 0 identity,
/// `Max`/`Min` peel the first element under a `k > 0` guard (NaN-propagating, no
/// ±∞ literal — header-light, and no out-of-bounds read on an empty axis).
///
/// v1 scope (asserted, AOT build-time — reductions are not in the JIT vocabulary,
/// so these never fire across the `synthesize` trust boundary): a single input,
/// all-contiguous operands, float dtype. Multi-input (weighted) reductions,
/// strided/broadcast inputs, arbitrary axes, integer accumulation, and a
/// block-parallel tree fold (lower error + speed) are follow-ups.
fn emit_reduction(plan: &KernelPlan<'_>, ctype: &str, rop: ReduceOp) -> GeneratedKernel {
    let tag = match rop {
        ReduceOp::Sum => "sum",
        ReduceOp::Mean => "mean",
        ReduceOp::Max => "max",
        ReduceOp::Min => "min",
    };
    let name = format!(
        "baracuda_gen_{}_{}_reduce_{tag}",
        plan.op_name,
        dtype_tag(plan.dtype)
    );
    assert!(
        matches!(
            plan.dtype,
            ElementKind::F16
                | ElementKind::Bf16
                | ElementKind::F32
                | ElementKind::F32Strict
                | ElementKind::F64
        ),
        "reduction v1: float dtypes only (int needs integer-typed accumulation — follow-up); got {:?}",
        plan.dtype
    );
    assert!(
        plan.n_inputs == 1,
        "reduction v1: single-input only (multi-input needs per-operand stride/broadcast — follow-up); got {}",
        plan.n_inputs
    );
    assert!(
        (0..plan.key.n_operands as usize).all(|i| plan.key.operands[i].contig == Contiguity::Contig),
        "reduction v1: contiguous operands only (base = o*k assumes a dense last axis); got a strided/broadcast cell"
    );
    let n = plan.n_inputs;
    // Accumulate in double for f64 and f32-strict; float for f32/f16/bf16 (torch
    // folds f16/bf16 in f32). The leaf load up-converts the input to that width,
    // and the body is lowered in it (f32 math, or f64 for a double fold).
    let dbl = matches!(plan.dtype, ElementKind::F64 | ElementKind::F32Strict);
    let acc = if dbl { "double" } else { "float" };
    let zero = if dbl { "0.0" } else { "0.0f" };
    let load = |i: u8| match plan.dtype {
        ElementKind::F16 => format!("__half2float(in{i}[idx])"),
        ElementKind::Bf16 => format!("__bfloat162float(in{i}[idx])"),
        ElementKind::F32Strict => format!("(double)in{i}[idx]"),
        _ => format!("in{i}[idx]"), // f32 (float) / f64 (double) load natively
    };
    let elem = lower_expr(
        plan.body,
        &Lowering {
            leaf: &load,
            reduced: &|i| unreachable!("no Reduced leaf outside RowReduce: red{i}"),
            unary: &|op, x| if dbl { unary_f64(op, x) } else { unary_f32(op, x) },
            binary: &|op, a, b| {
                if dbl {
                    binary_f64(op, a, b)
                } else {
                    binary_f32(op, a, b)
                }
            },
        },
    );

    let mut s = header(plan, &name);
    for i in 0..n {
        s.push_str(&format!("    const {ctype}* __restrict__ in{i},\n"));
    }
    s.push_str(&format!("    {ctype}* __restrict__ out,\n"));
    s.push_str(&format!(
        "    long long n_out,\n    long long k{})\n{{\n",
        param_args(plan.body)
    ));
    s.push_str("    long long o = (long long)blockIdx.x * blockDim.x + threadIdx.x;\n");
    s.push_str("    long long stride = (long long)gridDim.x * blockDim.x;\n");
    s.push_str("    for (; o < n_out; o += stride) {\n");
    s.push_str("        long long base = o * k;\n");
    match rop {
        ReduceOp::Sum | ReduceOp::Mean => {
            s.push_str(&format!("        {acc} acc = {zero};\n"));
            s.push_str("        for (long long j = 0; j < k; ++j) {\n");
            s.push_str("            long long idx = base + j;\n");
            s.push_str(&format!("            acc += {elem};\n"));
            s.push_str("        }\n");
        }
        ReduceOp::Max | ReduceOp::Min => {
            let cmp = if matches!(rop, ReduceOp::Max) { ">" } else { "<" };
            // Seed from the first element under a k>0 guard (no ±∞ literal, and no
            // OOB read on an empty axis); a NaN element sticks (torch.amax/amin).
            s.push_str(&format!("        {acc} acc = {zero};\n"));
            s.push_str("        if (k > 0) {\n");
            s.push_str("            long long idx = base;\n");
            s.push_str(&format!("            acc = {elem};\n"));
            s.push_str("            for (long long j = 1; j < k; ++j) {\n");
            s.push_str("                idx = base + j;\n");
            s.push_str(&format!("                {acc} e = {elem};\n"));
            s.push_str(&format!("                acc = (e != e || e {cmp} acc) ? e : acc;\n"));
            s.push_str("            }\n");
            s.push_str("        }\n");
        }
    }
    let finalized = if matches!(rop, ReduceOp::Mean) {
        format!("acc / ({acc})k")
    } else {
        "acc".to_string()
    };
    let stored = match plan.dtype {
        ElementKind::F16 => format!("__float2half({finalized})"),
        ElementKind::Bf16 => format!("__float2bfloat16({finalized})"),
        _ => finalized,
    };
    s.push_str(&format!("        out[o] = {stored};\n"));
    s.push_str("    }\n}\n");
    GeneratedKernel { name, source: s }
}

/// Emit a **fused row reduction** ([`Access::RowReduce`]): one block per output
/// row, a warp-shuffle + shared-memory tree reduce per stage, then a full-width
/// elementwise epilogue. RmsNorm (1 stage) and Softmax (2 stages) are instances.
///
/// Each `block_*` helper broadcasts its result to *every* thread of the block, so a
/// stage's reduced scalar lives in a uniform per-thread register `r{i}` —
/// `Reduced(i)` lowers straight to it, with no `__shared__ row_red[]` round-trip
/// and no extra cross-row barrier (the helpers' internal barriers fully serialize
/// their shared reuse across stages and grid-stride rows). The accumulator is
/// `float` (`double` for f64 / f32-strict); f16/bf16 load up-convert and store
/// down-convert, exactly as [`emit_reduction`].
///
/// Correctness invariants (see the design panel): every `__syncthreads` (inside the
/// helpers) is reached by ALL threads — the row guard is the uniform grid-stride
/// `for (row = blockIdx.x; row < n_out; ...)`, NEVER a divergent per-thread early
/// return, so a refactor to per-thread row mapping would deadlock. `__shfl_down_sync`
/// uses the full `0xffffffff` mask; the launch contract caps `blockDim.x <= 1024`
/// and (for warp uniformity) a multiple of 32.
fn emit_row_reduce(plan: &KernelPlan<'_>, ctype: &str) -> GeneratedKernel {
    let Access::RowReduce { stages, epilogue } = plan.access else {
        unreachable!("emit_row_reduce requires Access::RowReduce");
    };
    let dbl = matches!(plan.dtype, ElementKind::F64 | ElementKind::F32Strict);
    let acc = if dbl { "double" } else { "float" };
    let zero = if dbl { "0.0" } else { "0.0f" };
    let n = plan.n_inputs;
    let name = format!("baracuda_gen_{}_{}_rowreduce", plan.op_name, dtype_tag(plan.dtype));
    // Helpers are named per (op, dtype) so concatenating generated kernels into one
    // translation unit can never collide on a `__device__` symbol.
    let stem = format!("{}_{}", plan.op_name, dtype_tag(plan.dtype));

    // load(i), up-converting f16/bf16/f32-strict to the accumulate type. The index
    // is role-aware (validate guarantees the roles): a row-streamed input (`x`) loads
    // `in_i[idx]` (idx = base+j); a per-column weight/bias loads `in_i[j]` (the same
    // value every row). Both `idx` and `j` are in scope in every stage fold + the
    // epilogue loop. (Validate forbids column inputs inside a stage `pre`, so stage
    // folds only ever see row-streamed loads — byte-identical to the single-input path.)
    let load = |i: u8| {
        let pos = match rr_role(plan.key.operands[i as usize]) {
            RrRole::RowStreamed => "idx",
            RrRole::ColBroadcast => "j",
        };
        match plan.dtype {
            ElementKind::F16 => format!("__half2float(in{i}[{pos}])"),
            ElementKind::Bf16 => format!("__bfloat162float(in{i}[{pos}])"),
            ElementKind::F32Strict => format!("(double)in{i}[{pos}]"),
            _ => format!("in{i}[{pos}]"),
        }
    };
    // Reduced(s) is the broadcast register from stage s.
    let red = |s: u8| format!("r{s}");
    let lower = |e: &ScalarExpr| {
        lower_expr(
            e,
            &Lowering {
                leaf: &load,
                reduced: &red,
                unary: &|op, x| if dbl { unary_f64(op, x) } else { unary_f32(op, x) },
                binary: &|op, a, b| {
                    if dbl {
                        binary_f64(op, a, b)
                    } else {
                        binary_f32(op, a, b)
                    }
                },
            },
        )
    };

    // Preamble: comment + dtype include + the block-reduce helpers (only the
    // combines the stages use), then the kernel signature. (We can't reuse
    // `header` here: the helpers must sit between the includes and `extern "C"`.)
    let mut s = format!(
        "// Generated by baracuda-kernelgen — do not edit.\n// op: {} | cell: {}\n",
        plan.op_name,
        plan.key.to_token()
    );
    if let Some(inc) = extra_include(plan.dtype) {
        s.push_str(inc);
    }
    s.push('\n');
    let mut ops = std::collections::HashSet::new();
    for st in stages {
        ops.insert(st.op);
    }
    emit_block_reducers(&mut s, acc, zero, &ops, &stem);
    s.push_str(&format!("extern \"C\" __global__ void {name}(\n"));
    for i in 0..n {
        s.push_str(&format!("    const {ctype}* __restrict__ in{i},\n"));
    }
    s.push_str(&format!("    {ctype}* __restrict__ out,\n"));
    s.push_str(&format!(
        "    long long n_out,\n    long long k{})\n{{\n",
        param_args(plan.body)
    ));
    // Uniform empty-axis guard (k is a single kernel arg): never skips a barrier
    // divergently, and defends the Max/Min seed against an OOB load.
    s.push_str("    if (k == 0) return;\n");
    s.push_str("    for (long long row = blockIdx.x; row < n_out; row += (long long)gridDim.x) {\n");
    s.push_str("        long long base = row * k;\n");

    for (i, st) in stages.iter().enumerate() {
        let pre = lower(&st.pre);
        s.push_str(&format!("        // stage {i}: {:?}\n", st.op));
        match st.op {
            ReduceOp::Sum | ReduceOp::Mean => {
                s.push_str(&format!("        {acc} acc{i} = {zero};\n"));
                s.push_str("        for (long long j = threadIdx.x; j < k; j += blockDim.x) {\n");
                s.push_str("            long long idx = base + j;\n");
                s.push_str(&format!("            acc{i} += {pre};\n"));
                s.push_str("        }\n");
                // block_sum broadcasts the row sum to every thread; Mean divides by
                // k (k>0 guaranteed by the guard above) — uniform in every thread.
                let fin = if matches!(st.op, ReduceOp::Mean) {
                    format!("block_sum_{stem}(acc{i}) / ({acc})k")
                } else {
                    format!("block_sum_{stem}(acc{i})")
                };
                s.push_str(&format!("        {acc} r{i} = {fin};\n"));
            }
            ReduceOp::Max | ReduceOp::Min => {
                let cmp = if matches!(st.op, ReduceOp::Max) { ">" } else { "<" };
                let suf = if matches!(st.op, ReduceOp::Max) { "max" } else { "min" };
                // Carry a `has` flag so idle / short-row lanes inject nothing and no
                // ±inf seed is needed (headerless); NaN sticks via `e != e`.
                s.push_str(&format!("        {acc} acc{i} = {zero}; int has{i} = 0;\n"));
                s.push_str("        for (long long j = threadIdx.x; j < k; j += blockDim.x) {\n");
                s.push_str("            long long idx = base + j;\n");
                s.push_str(&format!("            {acc} e = {pre};\n"));
                s.push_str(&format!(
                    "            if (!has{i} || e != e || e {cmp} acc{i}) {{ acc{i} = e; has{i} = 1; }}\n"
                ));
                s.push_str("        }\n");
                s.push_str(&format!("        {acc} r{i} = block_{suf}_{stem}(acc{i}, has{i});\n"));
            }
        }
    }

    // Epilogue: full-width output (out[idx], same shape as input), x re-read from
    // global, Reduced(i) read from the r{i} registers.
    let epi = lower(epilogue);
    let stored = match plan.dtype {
        ElementKind::F16 => format!("__float2half({epi})"),
        ElementKind::Bf16 => format!("__float2bfloat16({epi})"),
        _ => epi,
    };
    s.push_str("        for (long long j = threadIdx.x; j < k; j += blockDim.x) {\n");
    s.push_str("            long long idx = base + j;\n");
    s.push_str(&format!("            out[idx] = {stored};\n"));
    s.push_str("        }\n");
    s.push_str("    }\n}\n");
    GeneratedKernel { name, source: s }
}

/// Append the warp/block tree-reduce device helpers for the `ops` actually used,
/// typed by accumulator `acc` (float/double) and uniquely named per `stem`
/// (op+dtype). Each `block_*` broadcasts its result to all block threads.
///
/// Correctness: the full `0xffffffff` shuffle mask (all lanes run the same loop);
/// the cross-warp fold indexes `smem[threadIdx.x]` (NOT `lane` — a multi-warp
/// block must read distinct warp partials, not warp 0's duplicated) and reads only
/// the first `nwarps` slots; Sum pads out-of-range slots with the `0` identity;
/// Max/Min carry a `(value, has)` flag and peel real partials (no ±inf literal,
/// NaN-propagating to match `torch.amax`/`amin`).
fn emit_block_reducers(
    s: &mut String,
    acc: &str,
    zero: &str,
    ops: &std::collections::HashSet<ReduceOp>,
    stem: &str,
) {
    if ops.iter().any(|o| matches!(o, ReduceOp::Sum | ReduceOp::Mean)) {
        s.push_str(&format!(
            "__device__ __forceinline__ {acc} warp_sum_{stem}({acc} v) {{\n\
             \x20   for (int off = warpSize / 2; off > 0; off >>= 1)\n\
             \x20       v += __shfl_down_sync(0xffffffffu, v, off);\n\
             \x20   return v;\n\
             }}\n\
             __device__ __forceinline__ {acc} block_sum_{stem}({acc} v) {{\n\
             \x20   __shared__ {acc} smem[32];\n\
             \x20   int lane = threadIdx.x & (warpSize - 1);\n\
             \x20   int wid = threadIdx.x / warpSize;\n\
             \x20   int nwarps = (blockDim.x + warpSize - 1) / warpSize;\n\
             \x20   v = warp_sum_{stem}(v);\n\
             \x20   if (lane == 0) smem[wid] = v;\n\
             \x20   __syncthreads();\n\
             \x20   {acc} r = ((int)threadIdx.x < nwarps) ? smem[threadIdx.x] : {zero};\n\
             \x20   if (wid == 0) r = warp_sum_{stem}(r);\n\
             \x20   __shared__ {acc} bcast;\n\
             \x20   if (threadIdx.x == 0) bcast = r;\n\
             \x20   __syncthreads();\n\
             \x20   return bcast;\n\
             }}\n"
        ));
    }
    for (suf, cmp) in [("max", ">"), ("min", "<")] {
        let want = (suf == "max" && ops.contains(&ReduceOp::Max))
            || (suf == "min" && ops.contains(&ReduceOp::Min));
        if !want {
            continue;
        }
        s.push_str(&format!(
            "__device__ __forceinline__ void warp_{suf}_{stem}({acc}& v, int& has) {{\n\
             \x20   for (int off = warpSize / 2; off > 0; off >>= 1) {{\n\
             \x20       {acc} ov = __shfl_down_sync(0xffffffffu, v, off);\n\
             \x20       int oh = __shfl_down_sync(0xffffffffu, has, off);\n\
             \x20       if (oh && (!has || ov != ov || ov {cmp} v)) {{ v = ov; has = 1; }}\n\
             \x20   }}\n\
             }}\n\
             __device__ __forceinline__ {acc} block_{suf}_{stem}({acc} v, int has) {{\n\
             \x20   __shared__ {acc} sv[32]; __shared__ int sh[32];\n\
             \x20   int lane = threadIdx.x & (warpSize - 1);\n\
             \x20   int wid = threadIdx.x / warpSize;\n\
             \x20   int nwarps = (blockDim.x + warpSize - 1) / warpSize;\n\
             \x20   warp_{suf}_{stem}(v, has);\n\
             \x20   if (lane == 0) {{ sv[wid] = v; sh[wid] = has; }}\n\
             \x20   __syncthreads();\n\
             \x20   __shared__ {acc} bcast;\n\
             \x20   if (threadIdx.x == 0) {{\n\
             \x20       {acc} m = sv[0]; int mh = sh[0];\n\
             \x20       for (int i = 1; i < nwarps; ++i)\n\
             \x20           if (sh[i] && (!mh || sv[i] != sv[i] || sv[i] {cmp} m)) {{ m = sv[i]; mh = 1; }}\n\
             \x20       bcast = m;\n\
             \x20   }}\n\
             \x20   __syncthreads();\n\
             \x20   return bcast;\n\
             }}\n"
        ));
    }
    s.push('\n');
}

/// `true` if every iteration axis of `o` is a broadcast axis — its offset is
/// loop-invariant, so the load hoists out of the loop.
fn is_fully_broadcast(o: OperandKey, rank: usize) -> bool {
    rank > 0 && (0..rank).all(|d| o.bcast.is_set(d as u8))
}

/// Element-offset expression for an operand, dropping the terms for broadcast
/// axes (whose stride is known 0 at compile time).
fn offset_expr(o: OperandKey, stride_arr: &str, rank: usize) -> String {
    let mut terms = Vec::new();
    for d in 0..rank {
        if o.bcast.is_set(d as u8) {
            continue;
        }
        terms.push(format!("c{d}*{stride_arr}[{d}]"));
    }
    if terms.is_empty() {
        "0".to_string()
    } else {
        terms.join(" + ")
    }
}

/// Spell a [`UnaryOp`] applied to an already-lowered f32 inner expression.
/// Inner strings are atomic or parenthesized, so the function-call forms need no
/// extra wrapping; the operator forms wrap themselves. (`Sigmoid`/`Gelu`/`Silu`
/// reference the inner twice — fine for an atomic load; a temp-binding pass to
/// avoid recompute on compound inners is a follow-up.)
fn unary_f32(op: UnaryOp, x: String) -> String {
    match op {
        UnaryOp::Neg => format!("(-{x})"),
        UnaryOp::Abs => format!("fabsf({x})"),
        UnaryOp::Sqr => format!("({x}*{x})"),
        UnaryOp::Sqrt => format!("sqrtf({x})"),
        UnaryOp::Rsqrt => format!("rsqrtf({x})"),
        UnaryOp::Recip => format!("(1.0f/{x})"),
        UnaryOp::Exp => format!("expf({x})"),
        UnaryOp::Log => format!("logf({x})"),
        UnaryOp::Tanh => format!("tanhf({x})"),
        UnaryOp::Sigmoid => format!("(1.0f/(1.0f+expf(-{x})))"),
        // NaN-propagating: `NaN < 0` is false, so NaN passes through (matches
        // PyTorch). `fmaxf(x,0)` would scrub NaN to 0. (Inner duplicated — the
        // temp-binding pass that fixes recompute is a follow-up.)
        UnaryOp::Relu => format!("({x} < 0.0f ? 0.0f : {x})"),
        UnaryOp::Erf => format!("erff({x})"),
        UnaryOp::Gelu => format!("(0.5f*{x}*(1.0f+erff({x}*0.70710678f)))"),
        UnaryOp::Silu => format!("({x}*(1.0f/(1.0f+expf(-{x}))))"),
        UnaryOp::Sin => format!("sinf({x})"),
        UnaryOp::Cos => format!("cosf({x})"),
        UnaryOp::Floor => format!("floorf({x})"),
        UnaryOp::Ceil => format!("ceilf({x})"),
        UnaryOp::Round => format!("rintf({x})"), // ties to even
        UnaryOp::Sign => format!("({x} > 0.0f ? 1.0f : ({x} < 0.0f ? -1.0f : 0.0f))"),
        UnaryOp::Step => format!("({x} > 0.0f ? 1.0f : 0.0f)"), // heaviside(x, 0): step(0)=0
    }
}

/// Same as [`unary_f32`] but with f64 math-function names and double literals.
fn unary_f64(op: UnaryOp, x: String) -> String {
    match op {
        UnaryOp::Neg => format!("(-{x})"),
        UnaryOp::Abs => format!("fabs({x})"),
        UnaryOp::Sqr => format!("({x}*{x})"),
        UnaryOp::Sqrt => format!("sqrt({x})"),
        UnaryOp::Rsqrt => format!("rsqrt({x})"),
        UnaryOp::Recip => format!("(1.0/{x})"),
        UnaryOp::Exp => format!("exp({x})"),
        UnaryOp::Log => format!("log({x})"),
        UnaryOp::Tanh => format!("tanh({x})"),
        UnaryOp::Sigmoid => format!("(1.0/(1.0+exp(-{x})))"),
        UnaryOp::Relu => format!("({x} < 0.0 ? 0.0 : {x})"),
        UnaryOp::Erf => format!("erf({x})"),
        UnaryOp::Gelu => format!("(0.5*{x}*(1.0+erf({x}*0.7071067811865476)))"),
        UnaryOp::Silu => format!("({x}*(1.0/(1.0+exp(-{x}))))"),
        UnaryOp::Sin => format!("sin({x})"),
        UnaryOp::Cos => format!("cos({x})"),
        UnaryOp::Floor => format!("floor({x})"),
        UnaryOp::Ceil => format!("ceil({x})"),
        UnaryOp::Round => format!("rint({x})"), // ties to even
        UnaryOp::Sign => format!("({x} > 0.0 ? 1.0 : ({x} < 0.0 ? -1.0 : 0.0))"),
        UnaryOp::Step => format!("({x} > 0.0 ? 1.0 : 0.0)"), // heaviside(x, 0): step(0)=0
    }
}

/// Lower a unary op for `dtype`. f32/f64 use native math; f16/bf16 compute in
/// float (convert → f32 math → convert) — correct for every op, and it avoids
/// the incomplete `__half2` math-intrinsic set (no `h2tanh`/`h2erf`). Packed
/// `__half2` SIMD is a perf follow-up. Integer dtypes have no unary math.
fn cuda_unary(op: UnaryOp, x: String, dtype: ElementKind) -> String {
    match dtype {
        ElementKind::F32 | ElementKind::F32Strict => unary_f32(op, x),
        ElementKind::F64 => unary_f64(op, x),
        ElementKind::F16 => {
            format!("__float2half({})", unary_f32(op, format!("__half2float({x})")))
        }
        ElementKind::Bf16 => {
            format!(
                "__float2bfloat16({})",
                unary_f32(op, format!("__bfloat162float({x})"))
            )
        }
        other => panic!("cuda backend: no unary math for dtype {other:?}"),
    }
}

/// Non-infix binary op in f32 math.
///
/// `Maximum`/`Minimum` are **NaN-propagating** (a NaN operand ⇒ NaN out) —
/// matching `torch.maximum`/`minimum` and the house reference kernel
/// `binary_maximum_fp.cu`, which deliberately reserves `fmaxf`/`fminf` (IEEE
/// `maxNum`, NaN-*suppressing*) for a *separate* `Fmax`/`Fmin` op. So we emit the
/// compare-select, not `fmaxf`. (Operands appear 3× — the deferred temp-binding
/// pass, cf. relu/sigmoid, removes the recompute on compound inners.)
fn binary_f32(op: BinaryOp, a: String, b: String) -> String {
    match op {
        BinaryOp::Max => format!("({a} != {a} ? {a} : ({b} != {b} ? {b} : ({a} > {b} ? {a} : {b})))"),
        BinaryOp::Min => format!("({a} != {a} ? {a} : ({b} != {b} ? {b} : ({a} < {b} ? {a} : {b})))"),
        BinaryOp::Pow => format!("powf({a}, {b})"),
        // Floored remainder (torch.remainder, sign-of-divisor — Fuel's Op::Rem),
        // not C fmodf (sign-of-dividend). Operands appear twice (temp-binding TODO).
        BinaryOp::Rem => format!("({a} - floorf({a} / {b}) * {b})"),
    }
}

/// Same as [`binary_f32`] but with f64 math-function names.
fn binary_f64(op: BinaryOp, a: String, b: String) -> String {
    match op {
        BinaryOp::Max => format!("({a} != {a} ? {a} : ({b} != {b} ? {b} : ({a} > {b} ? {a} : {b})))"),
        BinaryOp::Min => format!("({a} != {a} ? {a} : ({b} != {b} ? {b} : ({a} < {b} ? {a} : {b})))"),
        BinaryOp::Pow => format!("pow({a}, {b})"),
        BinaryOp::Rem => format!("({a} - floor({a} / {b}) * {b})"),
    }
}

/// Lower a non-infix binary op for `dtype` (f32/f64 native; f16/bf16 compute in
/// float). Mirrors [`cuda_unary`]; integer binary-function math is a follow-up.
fn cuda_binary(op: BinaryOp, a: String, b: String, dtype: ElementKind) -> String {
    match dtype {
        ElementKind::F32 | ElementKind::F32Strict => binary_f32(op, a, b),
        ElementKind::F64 => binary_f64(op, a, b),
        ElementKind::F16 => format!(
            "__float2half({})",
            binary_f32(op, format!("__half2float({a})"), format!("__half2float({b})"))
        ),
        ElementKind::Bf16 => format!(
            "__float2bfloat16({})",
            binary_f32(
                op,
                format!("__bfloat162float({a})"),
                format!("__bfloat162float({b})")
            )
        ),
        other => panic!("cuda backend: no binary math for dtype {other:?}"),
    }
}

/// Runtime scalar-param indices used by `e`, ascending + unique.
fn params_used(e: &ScalarExpr) -> Vec<u8> {
    fn rec(e: &ScalarExpr, out: &mut std::collections::BTreeSet<u8>) {
        match e {
            ScalarExpr::Param(i) => {
                out.insert(*i);
            }
            ScalarExpr::Unary(_, x) => rec(x, out),
            ScalarExpr::Add(a, b)
            | ScalarExpr::Sub(a, b)
            | ScalarExpr::Mul(a, b)
            | ScalarExpr::Div(a, b)
            | ScalarExpr::Binary(_, a, b) => {
                rec(a, out);
                rec(b, out);
            }
            ScalarExpr::Input(_) | ScalarExpr::Const(_) | ScalarExpr::Reduced(_) => {}
        }
    }
    let mut set = std::collections::BTreeSet::new();
    rec(e, &mut set);
    set.into_iter().collect()
}

/// The trailing `, float p0, float p1, …` kernel-signature suffix for the op's
/// runtime scalar params (empty when the op has none).
fn param_args(e: &ScalarExpr) -> String {
    params_used(e)
        .iter()
        .map(|i| format!(", float p{i}"))
        .collect()
}

#[cfg(test)]
mod tests {
    use crate::ir::{input, param, OpDef};
    use crate::{generate, Cuda};
    use baracuda_kernels_types::{structure_key, ArchSku, ElementKind, OpCategory, OperandDesc};

    fn add_op(dtypes: &[ElementKind]) -> OpDef {
        OpDef::elementwise("add", 2, dtypes, input(0) + input(1))
    }

    fn binary_key(dt: ElementKind) -> baracuda_kernels_types::StructureKey {
        let a = OperandDesc::new(1, &[1 << 20], &[1], dt, 256);
        structure_key(OpCategory::BinaryElementwise, &[a, a, a], ArchSku::Sm89)
    }

    #[test]
    fn f32_contiguous_vectorizes_to_float4() {
        let k = generate(&add_op(&[ElementKind::F32]), &binary_key(ElementKind::F32), &Cuda);
        assert_eq!(k.name, "baracuda_gen_add_f32_co_v4");
        assert!(k.source.contains("float4 v0 = in0[i];"));
        assert!(k.source.contains("vo.x = (v0.x + v1.x);"));
        assert!(k.source.contains("vo.w = (v0.w + v1.w);"));
    }

    #[test]
    fn maximum_propagates_nan_and_step_excludes_zero() {
        use crate::ir::UnaryOp;
        // Maximum: NaN-propagating compare-select, not fmaxf (the house convention).
        let max = OpDef::elementwise("m", 2, &[ElementKind::F32], input(0).max(input(1)));
        let km = generate(&max, &binary_key(ElementKind::F32), &Cuda);
        assert!(!km.source.contains("fmaxf"));
        assert!(km.source.contains("!=")); // the NaN check
        // Step: heaviside(x, 0), strict `>` so step(0) = 0.
        let step = OpDef::elementwise("s", 1, &[ElementKind::F32], input(0).unary(UnaryOp::Step));
        let a = OperandDesc::new(1, &[1 << 20], &[1], ElementKind::F32, 256);
        let key = structure_key(OpCategory::UnaryElementwise, &[a, a], ArchSku::Sm89);
        let ks = generate(&step, &key, &Cuda);
        assert!(ks.source.contains("> 0.0f ? 1.0f : 0.0f"));
        assert!(!ks.source.contains(">= 0.0f"));
    }

    #[test]
    fn f64_contiguous_vectorizes_to_double2() {
        let k = generate(&add_op(&[ElementKind::F64]), &binary_key(ElementKind::F64), &Cuda);
        assert_eq!(k.name, "baracuda_gen_add_f64_co_v2");
        assert!(k.source.contains("double2 v0 = in0[i];"));
        assert!(k.source.contains("vo.x = (v0.x + v1.x);"));
        assert!(k.source.contains("vo.y = (v0.y + v1.y);"));
        assert!(!k.source.contains("vo.z")); // only two lanes
    }

    #[test]
    fn f16_falls_back_to_scalar_with_fp16_header() {
        // f16 keys as V8 but has no packed path yet → scalar, reusing the same
        // infix lowering (CUDA overloads + for __half).
        let k = generate(&add_op(&[ElementKind::F16]), &binary_key(ElementKind::F16), &Cuda);
        assert_eq!(k.name, "baracuda_gen_add_f16_scalar");
        assert!(k.source.contains("#include <cuda_fp16.h>"));
        assert!(k.source.contains("const __half* __restrict__ in0"));
        assert!(k.source.contains("out[i] = (in0[i] + in1[i]);"));
    }

    #[test]
    fn strided_2d_unravels() {
        // Transposed (column-major) views: all operands strided, none broadcast.
        let t = OperandDesc::new(2, &[8, 4], &[1, 8], ElementKind::F32, 256);
        let key = structure_key(OpCategory::BinaryElementwise, &[t, t, t], ArchSku::Sm89);
        let k = generate(&add_op(&[ElementKind::F32]), &key, &Cuda);
        assert_eq!(k.name, "baracuda_gen_add_f32_strided_r2");
        assert!(k.source.contains("long long c1 = lin % shape[1]; lin /= shape[1];"));
        assert!(k.source.contains("long long o0 = c0*s0[0] + c1*s0[1];"));
        assert!(k.source.contains("out[oo] = (in0[o0] + in1[o1]);"));
    }

    #[test]
    fn fully_broadcast_operand_is_hoisted() {
        let a = OperandDesc::new(2, &[4, 8], &[8, 1], ElementKind::F32, 256);
        let b = OperandDesc::new(2, &[4, 8], &[0, 0], ElementKind::F32, 256); // scalar broadcast
        let out = OperandDesc::new(2, &[4, 8], &[8, 1], ElementKind::F32, 256);
        let key = structure_key(OpCategory::BinaryElementwise, &[a, b, out], ArchSku::Sm89);
        let k = generate(&add_op(&[ElementKind::F32]), &key, &Cuda);
        assert_eq!(k.name, "baracuda_gen_add_f32_strided_r2");
        assert!(k.source.contains("float h1 = in1[0];")); // hoisted invariant load
        assert!(k.source.contains("out[oo] = (in0[o0] + h1);")); // uses the register
        assert!(!k.source.contains("long long o1 =")); // no per-iter offset for in1
    }

    #[test]
    fn fma_lane_splat_for_nested_expr() {
        let fma = OpDef::elementwise(
            "fma",
            3,
            &[ElementKind::F32],
            input(0) * input(1) + input(2),
        );
        let a = OperandDesc::new(1, &[1 << 20], &[1], ElementKind::F32, 256);
        let key = structure_key(OpCategory::TernaryElementwise, &[a, a, a, a], ArchSku::Sm89);
        let k = generate(&fma, &key, &Cuda);
        assert!(k.source.contains("vo.y = ((v0.y * v1.y) + v2.y);"));
    }

    #[test]
    fn f32_unary_relu_lowers() {
        // y = relu(a + b), contiguous f32 V4.
        let op = OpDef::elementwise(
            "relu_add",
            2,
            &[ElementKind::F32],
            (input(0) + input(1)).relu(),
        );
        let a = OperandDesc::new(1, &[1 << 20], &[1], ElementKind::F32, 256);
        let key = structure_key(OpCategory::BinaryElementwise, &[a, a, a], ArchSku::Sm89);
        let k = generate(&op, &key, &Cuda);
        // NaN-propagating relu (select, not fmaxf).
        assert!(k
            .source
            .contains("vo.x = ((v0.x + v1.x) < 0.0f ? 0.0f : (v0.x + v1.x));"));
    }

    #[test]
    fn f16_unary_computes_in_float() {
        // f16 has no half2 path yet → scalar emit; unary computes in float.
        let op = OpDef::elementwise(
            "relu_add",
            2,
            &[ElementKind::F16],
            (input(0) + input(1)).relu(),
        );
        let a = OperandDesc::new(1, &[1 << 20], &[1], ElementKind::F16, 256);
        let key = structure_key(OpCategory::BinaryElementwise, &[a, a, a], ArchSku::Sm89);
        let k = generate(&op, &key, &Cuda);
        assert!(k.source.contains("#include <cuda_fp16.h>"));
        assert!(k.source.contains("__half2float((in0[i] + in1[i]))"));
        assert!(k.source.contains("< 0.0f ? 0.0f :")); // NaN-propagating relu, in float
    }

    #[test]
    fn scalar_param_kernel() {
        // y = relu(x * p0 + p1) — one input, two runtime scalar params.
        let op = OpDef::elementwise(
            "affine_relu",
            1,
            &[ElementKind::F32],
            (input(0) * param(0) + param(1)).relu(),
        );
        let a = OperandDesc::new(1, &[1 << 20], &[1], ElementKind::F32, 256);
        let key = structure_key(OpCategory::UnaryElementwise, &[a, a], ArchSku::Sm89);
        let k = generate(&op, &key, &Cuda);
        assert!(k.source.contains("long long nv, float p0, float p1)"));
        assert!(k.source.contains("((v0.x * p0) + p1)"));
    }

    fn reduce_key(in_dt: ElementKind) -> baracuda_kernels_types::StructureKey {
        // [256, 128] contiguous input, [256] output — reduce the last axis.
        let a = OperandDesc::new(2, &[256, 128], &[128, 1], in_dt, 256);
        let out = OperandDesc::new(1, &[256], &[1], in_dt, 256);
        structure_key(OpCategory::Reduction, &[a, out], ArchSku::Sm89)
    }

    #[test]
    fn reduction_mean_of_squares_f32() {
        use crate::ir::{ReduceOp, UnaryOp};
        // mean(x²) over the last axis — the RmsNorm core.
        let op = OpDef::reduction(
            "ms",
            1,
            &[ElementKind::F32],
            input(0).unary(UnaryOp::Sqr),
            ReduceOp::Mean,
        );
        let k = generate(&op, &reduce_key(ElementKind::F32), &Cuda);
        assert_eq!(k.name, "baracuda_gen_ms_f32_reduce_mean");
        assert!(k.source.contains("long long n_out,"));
        assert!(k.source.contains("    long long k)")); // runtime reduced extent
        assert!(k.source.contains("float acc = 0.0f;"));
        assert!(k.source.contains("long long idx = base + j;"));
        assert!(k.source.contains("acc += (in0[idx]*in0[idx]);"));
        assert!(k.source.contains("out[o] = acc / (float)k;"));
    }

    #[test]
    fn reduction_max_peels_first_and_propagates_nan() {
        use crate::ir::ReduceOp;
        let op = OpDef::reduction("amax", 1, &[ElementKind::F32], input(0), ReduceOp::Max);
        let k = generate(&op, &reduce_key(ElementKind::F32), &Cuda);
        assert_eq!(k.name, "baracuda_gen_amax_f32_reduce_max");
        assert!(!k.source.contains("INFINITY")); // seeded by the first element instead
        assert!(k.source.contains("if (k > 0) {")); // empty-axis guard, no OOB seed read
        assert!(k.source.contains("acc = in0[idx];")); // seed = first element
        assert!(k.source.contains("for (long long j = 1; j < k; ++j)"));
        // NaN-propagating select (e != e forces the swap), torch.amax semantics.
        assert!(k.source.contains("acc = (e != e || e > acc) ? e : acc;"));
    }

    #[test]
    fn reduction_f16_accumulates_in_float() {
        use crate::ir::ReduceOp;
        // f16 input/output, but the fold runs in float — precision + no __half2 sum.
        let op = OpDef::reduction("s", 1, &[ElementKind::F16], input(0), ReduceOp::Sum);
        let k = generate(&op, &reduce_key(ElementKind::F16), &Cuda);
        assert!(k.source.contains("#include <cuda_fp16.h>"));
        assert!(k.source.contains("const __half* __restrict__ in0"));
        assert!(k.source.contains("float acc = 0.0f;")); // float acc, not __half
        assert!(k.source.contains("acc += __half2float(in0[idx]);"));
        assert!(k.source.contains("out[o] = __float2half(acc);"));
    }

    #[test]
    fn reduction_f32strict_folds_in_double() {
        use crate::ir::ReduceOp;
        // Strict precision mode folds in double (a plain-float fold isn't reproducible
        // / correctly-rounded), then stores the single-rounded result to the f32 out.
        let op = OpDef::reduction("s", 1, &[ElementKind::F32Strict], input(0), ReduceOp::Sum);
        let k = generate(&op, &reduce_key(ElementKind::F32Strict), &Cuda);
        assert!(k.source.contains("double acc = 0.0;"));
        assert!(k.source.contains("acc += (double)in0[idx];"));
        assert!(k.source.contains("out[o] = acc;")); // double acc -> single round to float out
    }

    fn rr_key(dt: ElementKind, cat: OpCategory) -> baracuda_kernels_types::StructureKey {
        // full-width fused op: input + output share the [256, 128] contiguous shape.
        let a = OperandDesc::new(2, &[256, 128], &[128, 1], dt, 256);
        structure_key(cat, &[a, a], ArchSku::Sm89)
    }

    fn rmsnorm_op(dt: ElementKind) -> OpDef {
        use crate::ir::{konst, reduced, ReduceOp, ReduceStage, UnaryOp};
        // x * rsqrt(mean(x^2) + eps), eps baked as a finite Const.
        OpDef::row_reduce(
            "rmsnorm",
            1,
            &[dt],
            vec![ReduceStage {
                pre: input(0).unary(UnaryOp::Sqr).0,
                op: ReduceOp::Mean,
            }],
            input(0) * (reduced(0) + konst(1e-5)).unary(UnaryOp::Rsqrt),
        )
    }

    fn softmax_op(dt: ElementKind) -> OpDef {
        use crate::ir::{reduced, ReduceOp, ReduceStage};
        // exp(x - rowmax) / sum(exp(x - rowmax)) — numerically stable.
        OpDef::row_reduce(
            "softmax",
            1,
            &[dt],
            vec![
                ReduceStage { pre: input(0).0, op: ReduceOp::Max },
                ReduceStage {
                    pre: (input(0) - reduced(0)).exp().0,
                    op: ReduceOp::Sum,
                },
            ],
            (input(0) - reduced(0)).exp() / reduced(1),
        )
    }

    #[test]
    fn rowreduce_rmsnorm_block_tree_fold() {
        let k = generate(
            &rmsnorm_op(ElementKind::F32),
            &rr_key(ElementKind::F32, OpCategory::Normalization),
            &Cuda,
        );
        assert_eq!(k.name, "baracuda_gen_rmsnorm_f32_rowreduce");
        // warp-shuffle + shared-mem block reduce, full 0xffffffff mask.
        assert!(k.source.contains("__shfl_down_sync(0xffffffffu, v, off)"));
        assert!(k.source.contains("float block_sum_rmsnorm_f32(float v)"));
        // one block per row, grid-stride over rows; grid-stride fold within the row.
        assert!(k
            .source
            .contains("for (long long row = blockIdx.x; row < n_out; row += (long long)gridDim.x)"));
        assert!(k
            .source
            .contains("for (long long j = threadIdx.x; j < k; j += blockDim.x)"));
        // mean of squares -> rsqrt; full-width output; uniform empty-axis guard.
        assert!(k.source.contains("acc0 += (in0[idx]*in0[idx]);"));
        assert!(k.source.contains("block_sum_rmsnorm_f32(acc0) / (float)k"));
        assert!(k.source.contains("out[idx] = (in0[idx] * rsqrtf((r0 + 1e-5)));"));
        assert!(k.source.contains("if (k == 0) return;"));
    }

    #[test]
    fn rowreduce_cross_warp_indexes_threadidx_not_lane() {
        // The must-fix from the design review: the cross-warp fold reads DISTINCT
        // warp partials at smem[threadIdx.x], NEVER smem[lane] (which would refold
        // warp 0's partials for every multi-warp block — a silent wrong reduction).
        let k = generate(
            &rmsnorm_op(ElementKind::F32),
            &rr_key(ElementKind::F32, OpCategory::Normalization),
            &Cuda,
        );
        assert!(k.source.contains("smem[threadIdx.x]"));
        assert!(!k.source.contains("smem[lane]"));
    }

    #[test]
    fn rowreduce_softmax_two_stage_nan_max() {
        let k = generate(
            &softmax_op(ElementKind::F32),
            &rr_key(ElementKind::F32, OpCategory::Softmax),
            &Cuda,
        );
        assert_eq!(k.name, "baracuda_gen_softmax_f32_rowreduce");
        // stage 0: NaN-propagating max via the (value, has) flag, no ±inf literal.
        assert!(k.source.contains("block_max_softmax_f32"));
        assert!(!k.source.contains("INFINITY"));
        assert!(k.source.contains("if (!has0 || e != e || e > acc0)"));
        // stage 1 reads the rowmax register r0; numerically-stable exp(x - max).
        assert!(k.source.contains("acc1 += expf((in0[idx] - r0));"));
        // epilogue divides by the denom register r1.
        assert!(k.source.contains("out[idx] = (expf((in0[idx] - r0)) / r1);"));
    }

    #[test]
    fn rowreduce_f16_accumulates_in_float() {
        let k = generate(
            &rmsnorm_op(ElementKind::F16),
            &rr_key(ElementKind::F16, OpCategory::Normalization),
            &Cuda,
        );
        assert!(k.source.contains("#include <cuda_fp16.h>"));
        assert!(k.source.contains("const __half* __restrict__ in0"));
        assert!(k.source.contains("float block_sum_rmsnorm_f16(float v)")); // float acc
        assert!(k
            .source
            .contains("acc0 += (__half2float(in0[idx])*__half2float(in0[idx]));"));
        assert!(k.source.contains(
            "out[idx] = __float2half((__half2float(in0[idx]) * rsqrtf((r0 + 1e-5))));"
        ));
    }

    #[test]
    #[should_panic(expected = "references a stage not yet produced")]
    fn rowreduce_forward_reduced_ref_panics() {
        use crate::ir::{reduced, ReduceOp, ReduceStage};
        // A stage 0 `pre` referencing Reduced(0) (its own not-yet-produced result)
        // is a mis-authored op — validate_row_reduce must reject it at build_plan.
        let bad = OpDef::row_reduce(
            "bad",
            1,
            &[ElementKind::F32],
            vec![ReduceStage { pre: reduced(0).0, op: ReduceOp::Sum }],
            input(0) * reduced(0),
        );
        let _ = generate(&bad, &rr_key(ElementKind::F32, OpCategory::Normalization), &Cuda);
    }

    // --- multi-input RowReduce: weighted-RmsNorm + LayerNorm ---

    fn mi_key(dt: ElementKind, n_col: usize) -> baracuda_kernels_types::StructureKey {
        // x [256,128] full + n_col per-column [k] weight/bias (rank-aligned broadcast
        // view, stride [0,1]) + full-width output.
        let x = OperandDesc::new(2, &[256, 128], &[128, 1], dt, 256);
        let col = OperandDesc::new(2, &[256, 128], &[0, 1], dt, 256);
        let out = OperandDesc::new(2, &[256, 128], &[128, 1], dt, 256);
        let mut ops = vec![x];
        ops.extend(std::iter::repeat_n(col, n_col));
        ops.push(out);
        structure_key(OpCategory::Normalization, &ops, ArchSku::Sm89)
    }

    fn wrmsnorm_op(dt: ElementKind) -> OpDef {
        use crate::ir::{konst, reduced, ReduceOp, ReduceStage, UnaryOp};
        // x * rsqrt(mean(x^2) + eps) * weight; in0=x (row), in1=weight [k] (column).
        OpDef::row_reduce(
            "wrmsnorm",
            2,
            &[dt],
            vec![ReduceStage {
                pre: input(0).unary(UnaryOp::Sqr).0,
                op: ReduceOp::Mean,
            }],
            input(0) * (reduced(0) + konst(1e-5)).unary(UnaryOp::Rsqrt) * input(1),
        )
    }

    fn layernorm_op(dt: ElementKind) -> OpDef {
        use crate::ir::{konst, reduced, ReduceOp, ReduceStage, UnaryOp};
        // (x-mean)*rsqrt(var+eps)*weight + bias; in0=x, in1=weight[k], in2=bias[k].
        OpDef::row_reduce(
            "layernorm",
            3,
            &[dt],
            vec![
                ReduceStage { pre: input(0).0, op: ReduceOp::Mean },
                ReduceStage {
                    pre: (input(0) - reduced(0)).unary(UnaryOp::Sqr).0,
                    op: ReduceOp::Mean,
                },
            ],
            (input(0) - reduced(0)) * (reduced(1) + konst(1e-5)).unary(UnaryOp::Rsqrt) * input(1)
                + input(2),
        )
    }

    #[test]
    fn rowreduce_weighted_rmsnorm_column_index() {
        let k = generate(&wrmsnorm_op(ElementKind::F32), &mi_key(ElementKind::F32, 1), &Cuda);
        assert!(k.source.contains("const float* __restrict__ in1,")); // weight operand
        // stage reduces only the row-streamed x (in0[idx]); column weight only in
        // the epilogue, indexed in1[j] (per-column) not in1[idx] (per-element).
        assert!(k.source.contains("acc0 += (in0[idx]*in0[idx]);"));
        assert!(k.source.contains("out[idx] = ((in0[idx] * rsqrtf((r0 + 1e-5))) * in1[j]);"));
        assert!(!k.source.contains("in1[idx]"));
    }

    #[test]
    fn rowreduce_layernorm_stable_two_pass_with_weight_bias() {
        let k = generate(&layernorm_op(ElementKind::F32), &mi_key(ElementKind::F32, 2), &Cuda);
        assert!(k.source.contains("const float* __restrict__ in2,")); // bias operand
        // stage 0 mean; stage 1 = mean of squared DEVIATIONS (the stable two-pass
        // var, not the cancellation-prone mean(x^2)-mean(x)^2).
        assert!(k.source.contains("acc0 += in0[idx];"));
        assert!(k.source.contains("acc1 += ((in0[idx] - r0)*(in0[idx] - r0));"));
        // epilogue: (x-mean)*rsqrt(var+eps)*weight[j] + bias[j].
        assert!(k.source.contains(
            "out[idx] = ((((in0[idx] - r0) * rsqrtf((r1 + 1e-5))) * in1[j]) + in2[j]);"
        ));
        assert!(!k.source.contains("in1[idx]") && !k.source.contains("in2[idx]"));
    }

    #[test]
    #[should_panic(expected = "per-column")]
    fn rowreduce_bare_rank1_weight_rejected() {
        // The must-fix OOB guard: a weight passed as a BARE rank-1 [k] tensor (not a
        // rank-aligned [n_out,k] broadcast view) has an empty bcast mask -> would
        // misclassify as a second row-streamed input and read in1[row*k+j] past its
        // k elements. validate must reject it loudly.
        let x = OperandDesc::new(2, &[256, 128], &[128, 1], ElementKind::F32, 256);
        let bare_w = OperandDesc::new(1, &[128], &[1], ElementKind::F32, 256); // bare [K]
        let out = OperandDesc::new(2, &[256, 128], &[128, 1], ElementKind::F32, 256);
        let key = structure_key(OpCategory::Normalization, &[x, bare_w, out], ArchSku::Sm89);
        let _ = generate(&wrmsnorm_op(ElementKind::F32), &key, &Cuda);
    }

    #[test]
    #[should_panic(expected = "epilogue-only")]
    fn rowreduce_column_input_in_stage_rejected() {
        use crate::ir::{ReduceOp, ReduceStage};
        // Reducing a per-column operand is nonsense — a stage.pre referencing the
        // column weight (Input1) must be rejected.
        let bad = OpDef::row_reduce(
            "bad",
            2,
            &[ElementKind::F32],
            vec![ReduceStage {
                pre: (input(0) * input(1)).0,
                op: ReduceOp::Mean,
            }],
            input(0) * input(1),
        );
        let _ = generate(&bad, &mi_key(ElementKind::F32, 1), &Cuda);
    }
}
