//! CUDA C++ lowering — the one backend-specific module (v1).
//!
//! Everything CUDA-shaped (the vector types, `__global__`, the
//! `blockIdx`/`blockDim` launch indexing, the fp16/bf16 headers) lives here. The
//! math itself is lowered by the language-neutral [`crate::backend::lower_expr`]
//! — and reused verbatim across dtypes, because CUDA overloads `+ - * /` for
//! `__half` / `__nv_bfloat16` the same as for `float`.

use crate::backend::{lower_expr, Backend, GeneratedKernel, Lowering};
use crate::ir::{BinaryOp, ScalarExpr, UnaryOp};
use crate::plan::{KernelPlan, Schedule};
use baracuda_kernels_types::{ElementKind, OperandKey};

/// The CUDA C++ backend. Lowers a [`KernelPlan`] to `.cu` source.
#[derive(Copy, Clone, Debug, Default)]
pub struct Cuda;

impl Backend for Cuda {
    fn name(&self) -> &str {
        "cuda"
    }

    fn lower(&self, plan: &KernelPlan<'_>) -> GeneratedKernel {
        let Some(ctype) = scalar_ctype(plan.dtype) else {
            panic!("cuda backend: unsupported dtype {:?}", plan.dtype);
        };
        assert!(
            params_used(plan.body).is_empty()
                || matches!(plan.dtype, ElementKind::F32 | ElementKind::F32Strict),
            "cuda backend v1: scalar params are f32-only for now (dtype {:?})",
            plan.dtype
        );
        match plan.schedule {
            Schedule::Vectorized { width } => match vector_type(plan.dtype, width) {
                Some((vty, lanes)) => emit_vectorized(plan, vty, lanes),
                // dtype has no packed vector path yet (e.g. f16 V8): fall back to
                // scalar — still correct, and still gets the narrower-dtype
                // bandwidth win.
                None => emit_scalar(plan, ctype),
            },
            Schedule::Scalar => emit_scalar(plan, ctype),
            Schedule::Strided => emit_strided(plan, ctype),
        }
    }
}

/// CUDA scalar type for a dtype, or `None` if the backend can't lower it yet.
fn scalar_ctype(dt: ElementKind) -> Option<&'static str> {
    Some(match dt {
        ElementKind::F32 | ElementKind::F32Strict => "float",
        ElementKind::F64 => "double",
        ElementKind::F16 => "__half",
        ElementKind::Bf16 => "__nv_bfloat16",
        ElementKind::I32 => "int",
        ElementKind::I64 => "long long",
        _ => return None,
    })
}

/// Extra header a dtype needs (fp16 / bf16 device operators), if any.
fn extra_include(dt: ElementKind) -> Option<&'static str> {
    match dt {
        ElementKind::F16 => Some("#include <cuda_fp16.h>\n"),
        ElementKind::Bf16 => Some("#include <cuda_bf16.h>\n"),
        _ => None,
    }
}

/// Vector type + lane names for a `(dtype, width)` the backend can vectorize, or
/// `None` to fall back to scalar. f16/bf16 packed vectorization (`half2`
/// intrinsics) is a follow-up.
fn vector_type(dt: ElementKind, width: u32) -> Option<(&'static str, &'static [&'static str])> {
    match (dt, width) {
        (ElementKind::F32 | ElementKind::F32Strict, 4) => Some(("float4", &["x", "y", "z", "w"])),
        (ElementKind::F32 | ElementKind::F32Strict, 2) => Some(("float2", &["x", "y"])),
        (ElementKind::F64, 2) => Some(("double2", &["x", "y"])),
        _ => None,
    }
}

/// Short dtype tag for generated symbol names. Only called for dtypes that pass
/// [`scalar_ctype`].
fn dtype_tag(dt: ElementKind) -> &'static str {
    match dt {
        ElementKind::F32 => "f32",
        ElementKind::F32Strict => "f32s",
        ElementKind::F64 => "f64",
        ElementKind::F16 => "f16",
        ElementKind::Bf16 => "bf16",
        ElementKind::I32 => "i32",
        ElementKind::I64 => "i64",
        _ => "x",
    }
}

fn header(plan: &KernelPlan<'_>, name: &str) -> String {
    // Header-light, portable device source: no `<cstdint>` / `<cuda_runtime.h>`,
    // so the SAME source compiles under both nvcc (AOT) and nvrtc (JIT). Device
    // built-ins (`threadIdx`, `float4`, `__global__`) are implicit in both; the
    // 64-bit index type is the built-in `long long`. Only the fp16/bf16 operator
    // headers are included (nvrtc bundles them), and only when the dtype needs them.
    let mut h = format!(
        "// Generated by baracuda-kernelgen — do not edit.\n\
         // op: {} | cell: {}\n",
        plan.op_name,
        plan.key.to_token(),
    );
    if let Some(inc) = extra_include(plan.dtype) {
        h.push_str(inc);
    }
    h.push('\n');
    h.push_str(&format!("extern \"C\" __global__ void {name}(\n"));
    h
}

fn emit_vectorized(plan: &KernelPlan<'_>, vty: &str, lanes: &[&str]) -> GeneratedKernel {
    let name = format!(
        "baracuda_gen_{}_{}_co_v{}",
        plan.op_name,
        dtype_tag(plan.dtype),
        lanes.len()
    );
    let n = plan.n_inputs;
    let mut s = header(plan, &name);
    for i in 0..n {
        s.push_str(&format!("    const {vty}* __restrict__ in{i},\n"));
    }
    s.push_str(&format!("    {vty}* __restrict__ out,\n"));
    s.push_str(&format!("    long long nv{})\n{{\n", param_args(plan.body)));
    s.push_str("    long long i = (long long)blockIdx.x * blockDim.x + threadIdx.x;\n");
    s.push_str("    long long step = (long long)gridDim.x * blockDim.x;\n");
    s.push_str("    for (; i < nv; i += step) {\n");
    for i in 0..n {
        s.push_str(&format!("        {vty} v{i} = in{i}[i];\n"));
    }
    s.push_str(&format!("        {vty} vo;\n"));
    for lane in lanes {
        let acc = |idx: u8| format!("v{idx}.{lane}");
        s.push_str(&format!("        vo.{lane} = {};\n", lower_expr(
            plan.body,
            &Lowering {
                leaf: &acc,
                unary: &|op, x| cuda_unary(op, x, plan.dtype),
                binary: &|op, a, b| cuda_binary(op, a, b, plan.dtype),
            },
        )));
    }
    s.push_str("        out[i] = vo;\n    }\n}\n");
    GeneratedKernel { name, source: s }
}

fn emit_scalar(plan: &KernelPlan<'_>, ctype: &str) -> GeneratedKernel {
    let name = format!("baracuda_gen_{}_{}_scalar", plan.op_name, dtype_tag(plan.dtype));
    let n = plan.n_inputs;
    let mut s = header(plan, &name);
    for i in 0..n {
        s.push_str(&format!("    const {ctype}* __restrict__ in{i},\n"));
    }
    s.push_str(&format!("    {ctype}* __restrict__ out,\n"));
    s.push_str(&format!("    long long n{})\n{{\n", param_args(plan.body)));
    s.push_str("    long long i = (long long)blockIdx.x * blockDim.x + threadIdx.x;\n");
    s.push_str("    long long step = (long long)gridDim.x * blockDim.x;\n");
    let acc = |idx: u8| format!("in{idx}[i]");
    s.push_str(&format!(
        "    for (; i < n; i += step) out[i] = {};\n",
        lower_expr(
            plan.body,
            &Lowering {
                leaf: &acc,
                unary: &|op, x| cuda_unary(op, x, plan.dtype),
                binary: &|op, a, b| cuda_binary(op, a, b, plan.dtype),
            },
        )
    ));
    s.push_str("}\n");
    GeneratedKernel { name, source: s }
}

fn emit_strided(plan: &KernelPlan<'_>, ctype: &str) -> GeneratedKernel {
    let rank = plan.key.rank as usize;
    let n = plan.n_inputs as usize;
    let name = format!(
        "baracuda_gen_{}_{}_strided_r{}",
        plan.op_name,
        dtype_tag(plan.dtype),
        rank
    );
    let mut s = header(plan, &name);
    for i in 0..n {
        s.push_str(&format!("    const {ctype}* __restrict__ in{i},\n"));
    }
    s.push_str(&format!("    {ctype}* __restrict__ out,\n"));
    s.push_str("    const long long* __restrict__ shape,\n");
    for i in 0..n {
        s.push_str(&format!("    const long long* __restrict__ s{i},\n"));
    }
    s.push_str("    const long long* __restrict__ so,\n");
    s.push_str(&format!("    long long n{})\n{{\n", param_args(plan.body)));
    // Hoist fully-broadcast inputs: their offset is loop-invariant, load once.
    for k in 0..n {
        if is_fully_broadcast(plan.key.operands[k], rank) {
            s.push_str(&format!("    {ctype} h{k} = in{k}[0];\n"));
        }
    }
    s.push_str("    long long i = (long long)blockIdx.x * blockDim.x + threadIdx.x;\n");
    s.push_str("    long long step = (long long)gridDim.x * blockDim.x;\n");
    s.push_str("    for (; i < n; i += step) {\n");
    s.push_str("        long long lin = i;\n");
    // Row-major unravel (last axis fastest), unrolled over the iteration rank.
    for d in (0..rank).rev() {
        s.push_str(&format!(
            "        long long c{d} = lin % shape[{d}]; lin /= shape[{d}];\n"
        ));
    }
    for k in 0..n {
        if !is_fully_broadcast(plan.key.operands[k], rank) {
            let off = offset_expr(plan.key.operands[k], &format!("s{k}"), rank);
            s.push_str(&format!("        long long o{k} = {off};\n"));
        }
    }
    let oo = offset_expr(plan.key.operands[n], "so", rank);
    s.push_str(&format!("        long long oo = {oo};\n"));
    let acc = |idx: u8| {
        if is_fully_broadcast(plan.key.operands[idx as usize], rank) {
            format!("h{idx}")
        } else {
            format!("in{idx}[o{idx}]")
        }
    };
    s.push_str(&format!("        out[oo] = {};\n", lower_expr(
            plan.body,
            &Lowering {
                leaf: &acc,
                unary: &|op, x| cuda_unary(op, x, plan.dtype),
                binary: &|op, a, b| cuda_binary(op, a, b, plan.dtype),
            },
        )));
    s.push_str("    }\n}\n");
    GeneratedKernel { name, source: s }
}

/// `true` if every iteration axis of `o` is a broadcast axis — its offset is
/// loop-invariant, so the load hoists out of the loop.
fn is_fully_broadcast(o: OperandKey, rank: usize) -> bool {
    rank > 0 && (0..rank).all(|d| o.bcast.is_set(d as u8))
}

/// Element-offset expression for an operand, dropping the terms for broadcast
/// axes (whose stride is known 0 at compile time).
fn offset_expr(o: OperandKey, stride_arr: &str, rank: usize) -> String {
    let mut terms = Vec::new();
    for d in 0..rank {
        if o.bcast.is_set(d as u8) {
            continue;
        }
        terms.push(format!("c{d}*{stride_arr}[{d}]"));
    }
    if terms.is_empty() {
        "0".to_string()
    } else {
        terms.join(" + ")
    }
}

/// Spell a [`UnaryOp`] applied to an already-lowered f32 inner expression.
/// Inner strings are atomic or parenthesized, so the function-call forms need no
/// extra wrapping; the operator forms wrap themselves. (`Sigmoid`/`Gelu`/`Silu`
/// reference the inner twice — fine for an atomic load; a temp-binding pass to
/// avoid recompute on compound inners is a follow-up.)
fn unary_f32(op: UnaryOp, x: String) -> String {
    match op {
        UnaryOp::Neg => format!("(-{x})"),
        UnaryOp::Abs => format!("fabsf({x})"),
        UnaryOp::Sqr => format!("({x}*{x})"),
        UnaryOp::Sqrt => format!("sqrtf({x})"),
        UnaryOp::Rsqrt => format!("rsqrtf({x})"),
        UnaryOp::Recip => format!("(1.0f/{x})"),
        UnaryOp::Exp => format!("expf({x})"),
        UnaryOp::Log => format!("logf({x})"),
        UnaryOp::Tanh => format!("tanhf({x})"),
        UnaryOp::Sigmoid => format!("(1.0f/(1.0f+expf(-{x})))"),
        // NaN-propagating: `NaN < 0` is false, so NaN passes through (matches
        // PyTorch). `fmaxf(x,0)` would scrub NaN to 0. (Inner duplicated — the
        // temp-binding pass that fixes recompute is a follow-up.)
        UnaryOp::Relu => format!("({x} < 0.0f ? 0.0f : {x})"),
        UnaryOp::Erf => format!("erff({x})"),
        UnaryOp::Gelu => format!("(0.5f*{x}*(1.0f+erff({x}*0.70710678f)))"),
        UnaryOp::Silu => format!("({x}*(1.0f/(1.0f+expf(-{x}))))"),
        UnaryOp::Sin => format!("sinf({x})"),
        UnaryOp::Cos => format!("cosf({x})"),
        UnaryOp::Floor => format!("floorf({x})"),
        UnaryOp::Ceil => format!("ceilf({x})"),
        UnaryOp::Round => format!("rintf({x})"), // ties to even
        UnaryOp::Sign => format!("({x} > 0.0f ? 1.0f : ({x} < 0.0f ? -1.0f : 0.0f))"),
        UnaryOp::Step => format!("({x} > 0.0f ? 1.0f : 0.0f)"), // heaviside(x, 0): step(0)=0
    }
}

/// Same as [`unary_f32`] but with f64 math-function names and double literals.
fn unary_f64(op: UnaryOp, x: String) -> String {
    match op {
        UnaryOp::Neg => format!("(-{x})"),
        UnaryOp::Abs => format!("fabs({x})"),
        UnaryOp::Sqr => format!("({x}*{x})"),
        UnaryOp::Sqrt => format!("sqrt({x})"),
        UnaryOp::Rsqrt => format!("rsqrt({x})"),
        UnaryOp::Recip => format!("(1.0/{x})"),
        UnaryOp::Exp => format!("exp({x})"),
        UnaryOp::Log => format!("log({x})"),
        UnaryOp::Tanh => format!("tanh({x})"),
        UnaryOp::Sigmoid => format!("(1.0/(1.0+exp(-{x})))"),
        UnaryOp::Relu => format!("({x} < 0.0 ? 0.0 : {x})"),
        UnaryOp::Erf => format!("erf({x})"),
        UnaryOp::Gelu => format!("(0.5*{x}*(1.0+erf({x}*0.7071067811865476)))"),
        UnaryOp::Silu => format!("({x}*(1.0/(1.0+exp(-{x}))))"),
        UnaryOp::Sin => format!("sin({x})"),
        UnaryOp::Cos => format!("cos({x})"),
        UnaryOp::Floor => format!("floor({x})"),
        UnaryOp::Ceil => format!("ceil({x})"),
        UnaryOp::Round => format!("rint({x})"), // ties to even
        UnaryOp::Sign => format!("({x} > 0.0 ? 1.0 : ({x} < 0.0 ? -1.0 : 0.0))"),
        UnaryOp::Step => format!("({x} > 0.0 ? 1.0 : 0.0)"), // heaviside(x, 0): step(0)=0
    }
}

/// Lower a unary op for `dtype`. f32/f64 use native math; f16/bf16 compute in
/// float (convert → f32 math → convert) — correct for every op, and it avoids
/// the incomplete `__half2` math-intrinsic set (no `h2tanh`/`h2erf`). Packed
/// `__half2` SIMD is a perf follow-up. Integer dtypes have no unary math.
fn cuda_unary(op: UnaryOp, x: String, dtype: ElementKind) -> String {
    match dtype {
        ElementKind::F32 | ElementKind::F32Strict => unary_f32(op, x),
        ElementKind::F64 => unary_f64(op, x),
        ElementKind::F16 => {
            format!("__float2half({})", unary_f32(op, format!("__half2float({x})")))
        }
        ElementKind::Bf16 => {
            format!(
                "__float2bfloat16({})",
                unary_f32(op, format!("__bfloat162float({x})"))
            )
        }
        other => panic!("cuda backend: no unary math for dtype {other:?}"),
    }
}

/// Non-infix binary op in f32 math.
///
/// `Maximum`/`Minimum` are **NaN-propagating** (a NaN operand ⇒ NaN out) —
/// matching `torch.maximum`/`minimum` and the house reference kernel
/// `binary_maximum_fp.cu`, which deliberately reserves `fmaxf`/`fminf` (IEEE
/// `maxNum`, NaN-*suppressing*) for a *separate* `Fmax`/`Fmin` op. So we emit the
/// compare-select, not `fmaxf`. (Operands appear 3× — the deferred temp-binding
/// pass, cf. relu/sigmoid, removes the recompute on compound inners.)
fn binary_f32(op: BinaryOp, a: String, b: String) -> String {
    match op {
        BinaryOp::Max => format!("({a} != {a} ? {a} : ({b} != {b} ? {b} : ({a} > {b} ? {a} : {b})))"),
        BinaryOp::Min => format!("({a} != {a} ? {a} : ({b} != {b} ? {b} : ({a} < {b} ? {a} : {b})))"),
        BinaryOp::Pow => format!("powf({a}, {b})"),
        // Floored remainder (torch.remainder, sign-of-divisor — Fuel's Op::Rem),
        // not C fmodf (sign-of-dividend). Operands appear twice (temp-binding TODO).
        BinaryOp::Rem => format!("({a} - floorf({a} / {b}) * {b})"),
    }
}

/// Same as [`binary_f32`] but with f64 math-function names.
fn binary_f64(op: BinaryOp, a: String, b: String) -> String {
    match op {
        BinaryOp::Max => format!("({a} != {a} ? {a} : ({b} != {b} ? {b} : ({a} > {b} ? {a} : {b})))"),
        BinaryOp::Min => format!("({a} != {a} ? {a} : ({b} != {b} ? {b} : ({a} < {b} ? {a} : {b})))"),
        BinaryOp::Pow => format!("pow({a}, {b})"),
        BinaryOp::Rem => format!("({a} - floor({a} / {b}) * {b})"),
    }
}

/// Lower a non-infix binary op for `dtype` (f32/f64 native; f16/bf16 compute in
/// float). Mirrors [`cuda_unary`]; integer binary-function math is a follow-up.
fn cuda_binary(op: BinaryOp, a: String, b: String, dtype: ElementKind) -> String {
    match dtype {
        ElementKind::F32 | ElementKind::F32Strict => binary_f32(op, a, b),
        ElementKind::F64 => binary_f64(op, a, b),
        ElementKind::F16 => format!(
            "__float2half({})",
            binary_f32(op, format!("__half2float({a})"), format!("__half2float({b})"))
        ),
        ElementKind::Bf16 => format!(
            "__float2bfloat16({})",
            binary_f32(
                op,
                format!("__bfloat162float({a})"),
                format!("__bfloat162float({b})")
            )
        ),
        other => panic!("cuda backend: no binary math for dtype {other:?}"),
    }
}

/// Runtime scalar-param indices used by `e`, ascending + unique.
fn params_used(e: &ScalarExpr) -> Vec<u8> {
    fn rec(e: &ScalarExpr, out: &mut std::collections::BTreeSet<u8>) {
        match e {
            ScalarExpr::Param(i) => {
                out.insert(*i);
            }
            ScalarExpr::Unary(_, x) => rec(x, out),
            ScalarExpr::Add(a, b)
            | ScalarExpr::Sub(a, b)
            | ScalarExpr::Mul(a, b)
            | ScalarExpr::Div(a, b)
            | ScalarExpr::Binary(_, a, b) => {
                rec(a, out);
                rec(b, out);
            }
            ScalarExpr::Input(_) | ScalarExpr::Const(_) => {}
        }
    }
    let mut set = std::collections::BTreeSet::new();
    rec(e, &mut set);
    set.into_iter().collect()
}

/// The trailing `, float p0, float p1, …` kernel-signature suffix for the op's
/// runtime scalar params (empty when the op has none).
fn param_args(e: &ScalarExpr) -> String {
    params_used(e)
        .iter()
        .map(|i| format!(", float p{i}"))
        .collect()
}

#[cfg(test)]
mod tests {
    use crate::ir::{input, param, OpDef};
    use crate::{generate, Cuda};
    use baracuda_kernels_types::{structure_key, ArchSku, ElementKind, OpCategory, OperandDesc};

    fn add_op(dtypes: &[ElementKind]) -> OpDef {
        OpDef::elementwise("add", 2, dtypes, input(0) + input(1))
    }

    fn binary_key(dt: ElementKind) -> baracuda_kernels_types::StructureKey {
        let a = OperandDesc::new(1, &[1 << 20], &[1], dt, 256);
        structure_key(OpCategory::BinaryElementwise, &[a, a, a], ArchSku::Sm89)
    }

    #[test]
    fn f32_contiguous_vectorizes_to_float4() {
        let k = generate(&add_op(&[ElementKind::F32]), &binary_key(ElementKind::F32), &Cuda);
        assert_eq!(k.name, "baracuda_gen_add_f32_co_v4");
        assert!(k.source.contains("float4 v0 = in0[i];"));
        assert!(k.source.contains("vo.x = (v0.x + v1.x);"));
        assert!(k.source.contains("vo.w = (v0.w + v1.w);"));
    }

    #[test]
    fn maximum_propagates_nan_and_step_excludes_zero() {
        use crate::ir::UnaryOp;
        // Maximum: NaN-propagating compare-select, not fmaxf (the house convention).
        let max = OpDef::elementwise("m", 2, &[ElementKind::F32], input(0).max(input(1)));
        let km = generate(&max, &binary_key(ElementKind::F32), &Cuda);
        assert!(!km.source.contains("fmaxf"));
        assert!(km.source.contains("!=")); // the NaN check
        // Step: heaviside(x, 0), strict `>` so step(0) = 0.
        let step = OpDef::elementwise("s", 1, &[ElementKind::F32], input(0).unary(UnaryOp::Step));
        let a = OperandDesc::new(1, &[1 << 20], &[1], ElementKind::F32, 256);
        let key = structure_key(OpCategory::UnaryElementwise, &[a, a], ArchSku::Sm89);
        let ks = generate(&step, &key, &Cuda);
        assert!(ks.source.contains("> 0.0f ? 1.0f : 0.0f"));
        assert!(!ks.source.contains(">= 0.0f"));
    }

    #[test]
    fn f64_contiguous_vectorizes_to_double2() {
        let k = generate(&add_op(&[ElementKind::F64]), &binary_key(ElementKind::F64), &Cuda);
        assert_eq!(k.name, "baracuda_gen_add_f64_co_v2");
        assert!(k.source.contains("double2 v0 = in0[i];"));
        assert!(k.source.contains("vo.x = (v0.x + v1.x);"));
        assert!(k.source.contains("vo.y = (v0.y + v1.y);"));
        assert!(!k.source.contains("vo.z")); // only two lanes
    }

    #[test]
    fn f16_falls_back_to_scalar_with_fp16_header() {
        // f16 keys as V8 but has no packed path yet → scalar, reusing the same
        // infix lowering (CUDA overloads + for __half).
        let k = generate(&add_op(&[ElementKind::F16]), &binary_key(ElementKind::F16), &Cuda);
        assert_eq!(k.name, "baracuda_gen_add_f16_scalar");
        assert!(k.source.contains("#include <cuda_fp16.h>"));
        assert!(k.source.contains("const __half* __restrict__ in0"));
        assert!(k.source.contains("out[i] = (in0[i] + in1[i]);"));
    }

    #[test]
    fn strided_2d_unravels() {
        // Transposed (column-major) views: all operands strided, none broadcast.
        let t = OperandDesc::new(2, &[8, 4], &[1, 8], ElementKind::F32, 256);
        let key = structure_key(OpCategory::BinaryElementwise, &[t, t, t], ArchSku::Sm89);
        let k = generate(&add_op(&[ElementKind::F32]), &key, &Cuda);
        assert_eq!(k.name, "baracuda_gen_add_f32_strided_r2");
        assert!(k.source.contains("long long c1 = lin % shape[1]; lin /= shape[1];"));
        assert!(k.source.contains("long long o0 = c0*s0[0] + c1*s0[1];"));
        assert!(k.source.contains("out[oo] = (in0[o0] + in1[o1]);"));
    }

    #[test]
    fn fully_broadcast_operand_is_hoisted() {
        let a = OperandDesc::new(2, &[4, 8], &[8, 1], ElementKind::F32, 256);
        let b = OperandDesc::new(2, &[4, 8], &[0, 0], ElementKind::F32, 256); // scalar broadcast
        let out = OperandDesc::new(2, &[4, 8], &[8, 1], ElementKind::F32, 256);
        let key = structure_key(OpCategory::BinaryElementwise, &[a, b, out], ArchSku::Sm89);
        let k = generate(&add_op(&[ElementKind::F32]), &key, &Cuda);
        assert_eq!(k.name, "baracuda_gen_add_f32_strided_r2");
        assert!(k.source.contains("float h1 = in1[0];")); // hoisted invariant load
        assert!(k.source.contains("out[oo] = (in0[o0] + h1);")); // uses the register
        assert!(!k.source.contains("long long o1 =")); // no per-iter offset for in1
    }

    #[test]
    fn fma_lane_splat_for_nested_expr() {
        let fma = OpDef::elementwise(
            "fma",
            3,
            &[ElementKind::F32],
            input(0) * input(1) + input(2),
        );
        let a = OperandDesc::new(1, &[1 << 20], &[1], ElementKind::F32, 256);
        let key = structure_key(OpCategory::TernaryElementwise, &[a, a, a, a], ArchSku::Sm89);
        let k = generate(&fma, &key, &Cuda);
        assert!(k.source.contains("vo.y = ((v0.y * v1.y) + v2.y);"));
    }

    #[test]
    fn f32_unary_relu_lowers() {
        // y = relu(a + b), contiguous f32 V4.
        let op = OpDef::elementwise(
            "relu_add",
            2,
            &[ElementKind::F32],
            (input(0) + input(1)).relu(),
        );
        let a = OperandDesc::new(1, &[1 << 20], &[1], ElementKind::F32, 256);
        let key = structure_key(OpCategory::BinaryElementwise, &[a, a, a], ArchSku::Sm89);
        let k = generate(&op, &key, &Cuda);
        // NaN-propagating relu (select, not fmaxf).
        assert!(k
            .source
            .contains("vo.x = ((v0.x + v1.x) < 0.0f ? 0.0f : (v0.x + v1.x));"));
    }

    #[test]
    fn f16_unary_computes_in_float() {
        // f16 has no half2 path yet → scalar emit; unary computes in float.
        let op = OpDef::elementwise(
            "relu_add",
            2,
            &[ElementKind::F16],
            (input(0) + input(1)).relu(),
        );
        let a = OperandDesc::new(1, &[1 << 20], &[1], ElementKind::F16, 256);
        let key = structure_key(OpCategory::BinaryElementwise, &[a, a, a], ArchSku::Sm89);
        let k = generate(&op, &key, &Cuda);
        assert!(k.source.contains("#include <cuda_fp16.h>"));
        assert!(k.source.contains("__half2float((in0[i] + in1[i]))"));
        assert!(k.source.contains("< 0.0f ? 0.0f :")); // NaN-propagating relu, in float
    }

    #[test]
    fn scalar_param_kernel() {
        // y = relu(x * p0 + p1) — one input, two runtime scalar params.
        let op = OpDef::elementwise(
            "affine_relu",
            1,
            &[ElementKind::F32],
            (input(0) * param(0) + param(1)).relu(),
        );
        let a = OperandDesc::new(1, &[1 << 20], &[1], ElementKind::F32, 256);
        let key = structure_key(OpCategory::UnaryElementwise, &[a, a], ArchSku::Sm89);
        let k = generate(&op, &key, &Cuda);
        assert!(k.source.contains("long long nv, float p0, float p1)"));
        assert!(k.source.contains("((v0.x * p0) + p1)"));
    }
}
