//! The **dispatch-table artifact** — the committed `@generated` routing table.
//!
//! [`emit_dispatch_table`] serializes a [`DispatchTable`] to a dependency-free
//! Rust static — the exact discipline as [`crate::link::emit_link_registry`]:
//! sorted by token, deduped, `@generated`, human-diffable, closes cleanly. The
//! sys/plan crate `include!`s it and, at dispatch, computes the live
//! [`StructureKey`], projects to [`StructureKey::to_token`], and looks up the
//! route.
//!
//! The committed row is the **routing projection**
//! `(structure_key_token, winner_code, margin, provenance_code)` — enough to
//! route, byte-stable across runs (no wall-clock timestamp; the richer
//! [`HwStamp`](baracuda_kernel_vocab::HwStamp) stays on the in-memory table and
//! the bench CSV). [`parse_dispatch_table`] reads the projection back so the
//! emit→parse round-trip is a real, testable identity — the guard against a
//! token-codec drift between build time and runtime silently missing every row.

use baracuda_kernel_vocab::{DispatchEntry, DispatchTable, Implementor, Provenance};

/// Emit the generated Rust `dispatch_table` source — a static routing table the
/// runtime resolves per cell. Rows are sorted by `structure_key` token and
/// de-duplicated (last-writer-wins) for a stable, diff-friendly artifact.
///
/// Row shape: `(structure_key, winner, winner_entry, margin, provenance)` where
/// `winner`/`provenance` are the lowercase [`Implementor::code`]/
/// [`Provenance::code`] tokens, `winner_entry` is the winning kernel's entry
/// point (`"-"` when the winner has none, e.g. a vendor library) — load-bearing
/// for schedule **variants**, where several `Generated` candidates share one
/// cell token — and `margin` is `second_best_ns / winner_ns` formatted to fixed
/// precision (byte-stable).
#[must_use]
pub fn emit_dispatch_table(table: &DispatchTable) -> String {
    // Reverse before the stable sort so `dedup_by` (which keeps the first of each
    // equal-token run) retains the LAST writer of a duplicated token — the same
    // last-writer-wins semantics as `DispatchTable::normalize`, so a raw table
    // built by hand emits consistently with a normalized one.
    let mut sorted: Vec<&DispatchEntry> = table.entries.iter().rev().collect();
    sorted.sort_by(|a, b| a.structure_key.cmp(&b.structure_key));
    sorted.dedup_by(|a, b| a.structure_key == b.structure_key);

    let mut s = String::new();
    s.push_str("// @generated by baracuda-kernelgen — do not edit.\n");
    s.push_str("//! Per-cell routing decisions: which implementation serves each\n");
    s.push_str("//! StructureKey cell, with the measured margin and its provenance.\n");
    s.push_str("//! The runtime computes a live cell's `StructureKey::to_token()` and\n");
    s.push_str("//! looks it up here to route (design \u{a7}7 vendor-exclusion).\n\n");
    s.push_str(
        "/// `(structure_key, winner, winner_entry, margin, provenance)` for every routed cell.\n",
    );
    s.push_str("pub static BARACUDA_DISPATCH_TABLE: &[(&str, &str, &str, f64, &str)] = &[\n");
    for e in sorted {
        // Defense in depth: `merge` already rejects a non-finite margin, but clamp
        // here too so a hand-built table can never emit a bare `NaN`/`inf` — those
        // are not valid Rust f64 literals and would make the committed static fail
        // to compile. `1.0` = the conservative "no contest / no confidence" value.
        let margin = if e.margin.is_finite() { e.margin } else { 1.0 };
        s.push_str(&format!(
            "    (\"{}\", \"{}\", \"{}\", {:.6}, \"{}\"),\n",
            e.structure_key,
            e.winner.code(),
            e.winner_entry.as_deref().unwrap_or("-"),
            margin,
            e.provenance.code(),
        ));
    }
    s.push_str("];\n");
    s
}

/// Parse the routing projection back out of an [`emit_dispatch_table`] artifact.
///
/// Reconstructs each row as a [`DispatchEntry`] with `ranked` empty and
/// `measured_on` `None` (the artifact carries only the routing projection). A
/// row with an unknown implementor/provenance code or a malformed margin is
/// skipped — the artifact is `@generated`, so a parse miss means a schema drift
/// worth surfacing, never a silent guess.
///
/// This exists so the emit→parse identity is testable; it is not the runtime
/// path (the sys crate `include!`s the static directly).
#[must_use]
pub fn parse_dispatch_table(src: &str) -> Vec<DispatchEntry> {
    let mut out = Vec::new();
    for line in src.lines() {
        let t = line.trim();
        if !t.starts_with("(\"") {
            continue;
        }
        if let Some(entry) = parse_row(t) {
            out.push(entry);
        }
    }
    out
}

/// Parse one `("token", "winner", "entry", margin, "provenance"),` row. The
/// token/entry may contain `|`, `/`, `;` but never `"`, so the quoted fields
/// bound cleanly.
fn parse_row(row: &str) -> Option<DispatchEntry> {
    // token: between the first and second unescaped quote.
    let after_q1 = row.strip_prefix("(\"")?;
    let q2 = after_q1.find('"')?;
    let token = &after_q1[..q2];
    let rest = &after_q1[q2 + 1..]; // `, "winner", "entry", margin, "prov"),`

    // winner: the next quoted string.
    let wq1 = rest.find('"')?;
    let after_wq1 = &rest[wq1 + 1..];
    let wq2 = after_wq1.find('"')?;
    let winner = Implementor::from_code(&after_wq1[..wq2])?;
    let rest = &after_wq1[wq2 + 1..]; // `, "entry", margin, "prov"),`

    // winner_entry: the next quoted string; "-" means none.
    let eq1 = rest.find('"')?;
    let after_eq1 = &rest[eq1 + 1..];
    let eq2 = after_eq1.find('"')?;
    let entry = &after_eq1[..eq2];
    let winner_entry = (entry != "-").then(|| entry.to_string());
    let rest = &after_eq1[eq2 + 1..]; // `, margin, "prov"),`

    // provenance: the last quoted string.
    let pq1 = rest.find('"')?;
    let after_pq1 = &rest[pq1 + 1..];
    let pq2 = after_pq1.find('"')?;
    let provenance = Provenance::from_code(&after_pq1[..pq2])?;

    // margin: the number between the entry's close-quote and the comma before
    // the provenance quote.
    let margin_str = rest[..pq1]
        .trim()
        .trim_start_matches(',')
        .trim()
        .trim_end_matches(',')
        .trim();
    let margin: f64 = margin_str.parse().ok()?;
    // An `@generated` artifact never holds a non-finite margin (`emit` clamps and
    // `merge` rejects one). A `"NaN"`/`"inf"` row is therefore corruption — skip
    // it rather than route on an untrusted decision.
    if !margin.is_finite() {
        return None;
    }

    Some(DispatchEntry {
        structure_key: token.to_string(),
        winner,
        winner_entry,
        margin,
        ranked: Vec::new(),
        provenance,
        measured_on: None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use baracuda_kernel_vocab::{
        ArchSku, CandidateResult, ElementKind, OpCategory, OperandDesc, StructureKey, structure_key,
    };

    fn ew_token(dtype: ElementKind) -> String {
        let a = OperandDesc::new(2, &[128, 256], &[256, 1], dtype, 256);
        structure_key(OpCategory::BinaryElementwise, &[a, a, a], ArchSku::Sm89).to_token()
    }

    fn measured(token: String, winner: Implementor, margin: f64) -> DispatchEntry {
        DispatchEntry {
            structure_key: token,
            winner,
            winner_entry: None,
            margin,
            ranked: vec![CandidateResult {
                implementor: winner,
                median_ns: 1.0,
                entry_point: None,
            }],
            provenance: Provenance::Measured,
            measured_on: None,
        }
    }

    /// The routing projection of an entry — what the artifact carries and what a
    /// parse reconstructs (ranked/measured_on dropped).
    fn project(e: &DispatchEntry) -> DispatchEntry {
        DispatchEntry {
            structure_key: e.structure_key.clone(),
            winner: e.winner,
            winner_entry: e.winner_entry.clone(),
            margin: e.margin,
            ranked: Vec::new(),
            provenance: e.provenance,
            measured_on: None,
        }
    }

    #[test]
    fn artifact_is_sorted_deduped_valid_rust() {
        let zt = ew_token(ElementKind::F32); // "...|f32|..."
        let at = ew_token(ElementKind::F16); // "...|f16|..." sorts before f32
        let table = DispatchTable::from_entries(vec![
            measured(zt.clone(), Implementor::Cublas, 2.0),
            measured(at.clone(), Implementor::Generated, 1.5),
            measured(at.clone(), Implementor::Bespoke, 3.0), // dup token → collapses
        ]);
        let src = emit_dispatch_table(&table);
        assert!(
            src.contains(
                "pub static BARACUDA_DISPATCH_TABLE: &[(&str, &str, &str, f64, &str)] = &["
            )
        );
        // f16 token sorts before f32 token.
        let a = src.find(&at).unwrap();
        let z = src.find(&zt).unwrap();
        assert!(a < z, "rows must be sorted by structure-key token");
        // duplicate token collapsed to one row.
        assert_eq!(src.matches(&at).count(), 1, "duplicate token collapsed");
        assert!(src.trim_end().ends_with("];"), "closes cleanly");
    }

    #[test]
    fn emit_dedup_keeps_last_writer() {
        // A table built by hand (bypassing normalize) with a duplicated token but
        // different winners: emit's own dedup must keep the LAST writer, matching
        // DispatchTable::normalize.
        let tok = ew_token(ElementKind::F32);
        let table = DispatchTable {
            entries: vec![
                measured(tok.clone(), Implementor::Cublas, 2.0),
                measured(tok.clone(), Implementor::Generated, 2.0), // last writer
            ],
        };
        let src = emit_dispatch_table(&table);
        assert_eq!(src.matches(&tok).count(), 1, "one row survives");
        assert!(src.contains("\"gen\""), "last writer (Generated) survives");
        assert!(!src.contains("\"cublas\""), "first writer dropped");
    }

    #[test]
    fn emit_then_parse_round_trips_the_projection() {
        let table = DispatchTable::from_entries(vec![
            measured(ew_token(ElementKind::F32), Implementor::Cublas, 2.5),
            measured(ew_token(ElementKind::F16), Implementor::Generated, 1.25),
            DispatchEntry::seeded(ew_token(ElementKind::Bf16), Implementor::Cutlass),
        ]);
        let src = emit_dispatch_table(&table);
        let parsed = parse_dispatch_table(&src);

        let mut want: Vec<DispatchEntry> = table.entries.iter().map(project).collect();
        want.sort_by(|a, b| a.structure_key.cmp(&b.structure_key));
        assert_eq!(parsed.len(), want.len());
        for (p, w) in parsed.iter().zip(want.iter()) {
            assert_eq!(p.structure_key, w.structure_key);
            assert_eq!(p.winner, w.winner);
            assert_eq!(p.provenance, w.provenance);
            assert!((p.margin - w.margin).abs() < 1e-6, "margin round-trips");
        }
    }

    #[test]
    fn parsed_tokens_are_valid_structure_keys() {
        // Adversarial #5: a row's token must round-trip through the StructureKey
        // codec, or the runtime dispatcher computes a different token and misses.
        let table = DispatchTable::from_entries(vec![measured(
            ew_token(ElementKind::F32),
            Implementor::Generated,
            2.0,
        )]);
        let src = emit_dispatch_table(&table);
        for e in parse_dispatch_table(&src) {
            let key = StructureKey::from_token(&e.structure_key).expect("token parses");
            assert_eq!(key.to_token(), e.structure_key, "token is codec-stable");
        }
    }

    #[test]
    fn emission_is_order_independent() {
        // Adversarial #6: the artifact must be byte-stable regardless of the
        // order entries were measured/inserted.
        let f32 = ew_token(ElementKind::F32);
        let f16 = ew_token(ElementKind::F16);
        let a = DispatchTable::from_entries(vec![
            measured(f32.clone(), Implementor::Cublas, 2.0),
            measured(f16.clone(), Implementor::Generated, 1.5),
        ]);
        let b = DispatchTable::from_entries(vec![
            measured(f16, Implementor::Generated, 1.5),
            measured(f32, Implementor::Cublas, 2.0),
        ]);
        assert_eq!(emit_dispatch_table(&a), emit_dispatch_table(&b));
    }

    #[test]
    fn parse_skips_non_finite_margin_rows() {
        // A corrupt/hand-edited artifact carrying `NaN`/`inf` margins: those rows
        // must be skipped (never routed on), not parsed into a poisoned entry.
        let tok = ew_token(ElementKind::F32);
        let src = format!(
            "pub static BARACUDA_DISPATCH_TABLE: &[(&str, &str, f64, &str)] = &[\n    \
             (\"{tok}\", \"gen\", NaN, \"reported\"),\n    \
             (\"{tok}\", \"cublas\", inf, \"reported\"),\n];\n"
        );
        assert!(
            parse_dispatch_table(&src).is_empty(),
            "NaN/inf margin rows skipped"
        );
    }

    #[test]
    fn emit_clamps_non_finite_margin_to_compilable_literal() {
        // A hand-built table (bypassing merge) with a non-finite margin must still
        // emit a valid Rust f64 literal — never a bare `NaN`/`inf`.
        let tok = ew_token(ElementKind::F32);
        let table = DispatchTable {
            entries: vec![DispatchEntry {
                structure_key: tok,
                winner: Implementor::Cublas,
                winner_entry: None,
                margin: f64::INFINITY,
                ranked: Vec::new(),
                provenance: Provenance::Seeded,
                measured_on: None,
            }],
        };
        let src = emit_dispatch_table(&table);
        assert!(!src.contains("inf"), "no bare `inf` literal");
        assert!(!src.contains("NaN"), "no bare `NaN` literal");
        assert!(src.contains("1.000000"), "clamped to no-contest margin");
        // And the clamped artifact round-trips cleanly.
        assert_eq!(parse_dispatch_table(&src).len(), 1);
    }

    #[test]
    fn empty_table_emits_valid_empty_static() {
        let src = emit_dispatch_table(&DispatchTable::new());
        assert!(src.contains("BARACUDA_DISPATCH_TABLE"));
        assert!(src.trim_end().ends_with("];"));
        assert!(parse_dispatch_table(&src).is_empty());
    }
}
