//! CUDA emitter — lowers an [`OpDef`] at a [`StructureKey`] cell to `.cu` source.
//!
//! The schedule is chosen from the structure key: a contiguous + V4 cell emits a
//! `float4`-vectorized linear kernel; anything else falls back to a scalar
//! linear kernel (v1). The op body lowers to per-lane C expressions by walking
//! the [`ScalarExpr`] DAG with a lane accessor — the same expression yields the
//! scalar form `(in0[i] + in1[i])` or the vectorized form `(v0.x + v1.x)` purely
//! by swapping the leaf accessor. That is the payoff of describing op logic as
//! IR rather than opaque CUDA.

use crate::ir::{Access, OpDef, ScalarExpr};
use baracuda_kernels_types::{Contiguity, ElementKind, StructureKey, VecWidth};

/// A generated kernel: its `extern "C"` symbol name and CUDA C++ source.
#[derive(Clone, Debug)]
pub struct GeneratedKernel {
    /// The `extern "C"` symbol the kernel is exported as.
    pub name: String,
    /// The CUDA C++ source text.
    pub source: String,
}

/// Generate the specialized CUDA kernel for `op` at structure cell `key`.
///
/// v1 supports f32 elementwise ops on contiguous operands: vectorized (`float4`)
/// when every operand is `Contig` + `V4`, scalar otherwise. Strided / broadcast
/// schedules, other dtypes, and reductions are the next expansions.
///
/// # Panics
/// Panics if the op is not elementwise or the cell dtype is not f32 (the v1
/// emitter's documented scope).
#[must_use]
pub fn generate(op: &OpDef, key: &StructureKey) -> GeneratedKernel {
    assert!(
        matches!(op.access, Access::Elementwise),
        "v1 emitter handles elementwise ops only"
    );
    assert_eq!(
        key.dtype,
        ElementKind::F32,
        "v1 emitter handles f32 only"
    );
    let n = key.n_operands as usize;
    let all_contig_v4 = n > 0
        && (0..n).all(|k| {
            let o = key.operands[k];
            o.contig == Contiguity::Contig && o.vec_width == VecWidth::V4
        });
    if all_contig_v4 {
        emit_vec4(op, key)
    } else {
        emit_scalar(op, key)
    }
}

/// Lower a [`ScalarExpr`] to a C expression. `acc(i)` yields the C text for
/// input operand `i`'s value at the current position (e.g. `in0[i]` for scalar,
/// `v0.x` for a vector lane).
fn lower(e: &ScalarExpr, acc: &dyn Fn(u8) -> String) -> String {
    match e {
        ScalarExpr::Input(i) => acc(*i),
        ScalarExpr::Add(a, b) => format!("({} + {})", lower(a, acc), lower(b, acc)),
        ScalarExpr::Sub(a, b) => format!("({} - {})", lower(a, acc), lower(b, acc)),
        ScalarExpr::Mul(a, b) => format!("({} * {})", lower(a, acc), lower(b, acc)),
        ScalarExpr::Div(a, b) => format!("({} / {})", lower(a, acc), lower(b, acc)),
    }
}

fn header(op: &OpDef, key: &StructureKey, name: &str) -> String {
    format!(
        "// Generated by baracuda-kernelgen — do not edit.\n\
         // op: {} | cell: {}\n\
         #include <cstdint>\n#include <cuda_runtime.h>\n\n",
        op.name,
        key.to_token(),
    ) + &format!("extern \"C\" __global__ void {name}(\n")
}

fn emit_vec4(op: &OpDef, key: &StructureKey) -> GeneratedKernel {
    let name = format!("baracuda_gen_{}_f32_co_v4", op.name);
    let n = op.n_inputs;
    let mut s = header(op, key, &name);
    for i in 0..n {
        s.push_str(&format!("    const float4* __restrict__ in{i},\n"));
    }
    s.push_str("    float4* __restrict__ out,\n    int64_t n4)\n{\n");
    s.push_str("    int64_t i = (int64_t)blockIdx.x * blockDim.x + threadIdx.x;\n");
    s.push_str("    int64_t step = (int64_t)gridDim.x * blockDim.x;\n");
    s.push_str("    for (; i < n4; i += step) {\n");
    for i in 0..n {
        s.push_str(&format!("        float4 v{i} = in{i}[i];\n"));
    }
    s.push_str("        float4 vo;\n");
    for lane in ["x", "y", "z", "w"] {
        let acc = |idx: u8| format!("v{idx}.{lane}");
        s.push_str(&format!("        vo.{lane} = {};\n", lower(&op.body, &acc)));
    }
    s.push_str("        out[i] = vo;\n    }\n}\n");
    GeneratedKernel { name, source: s }
}

fn emit_scalar(op: &OpDef, key: &StructureKey) -> GeneratedKernel {
    let name = format!("baracuda_gen_{}_f32_scalar", op.name);
    let n = op.n_inputs;
    let mut s = header(op, key, &name);
    for i in 0..n {
        s.push_str(&format!("    const float* __restrict__ in{i},\n"));
    }
    s.push_str("    float* __restrict__ out,\n    int64_t n)\n{\n");
    s.push_str("    int64_t i = (int64_t)blockIdx.x * blockDim.x + threadIdx.x;\n");
    s.push_str("    int64_t step = (int64_t)gridDim.x * blockDim.x;\n");
    let acc = |idx: u8| format!("in{idx}[i]");
    s.push_str(&format!(
        "    for (; i < n; i += step) out[i] = {};\n}}\n",
        lower(&op.body, &acc)
    ));
    GeneratedKernel { name, source: s }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{input, OpDef};
    use baracuda_kernels_types::{structure_key, ArchSku, OperandDesc, OpCategory};

    fn add_op() -> OpDef {
        OpDef::elementwise("add", 2, &[ElementKind::F32], input(0) + input(1))
    }

    #[test]
    fn generates_vectorized_add() {
        let a = OperandDesc::new(1, &[1 << 20], &[1], ElementKind::F32, 256);
        let key = structure_key(OpCategory::BinaryElementwise, &[a, a, a], ArchSku::Sm89);
        let k = generate(&add_op(), &key);
        assert_eq!(k.name, "baracuda_gen_add_f32_co_v4");
        assert!(k.source.contains("extern \"C\" __global__"));
        assert!(k.source.contains("float4 v0 = in0[i];"));
        assert!(k.source.contains("float4 v1 = in1[i];"));
        assert!(k.source.contains("vo.x = (v0.x + v1.x);"));
        assert!(k.source.contains("vo.w = (v0.w + v1.w);"));
        assert!(k.source.contains("out[i] = vo;"));
    }

    #[test]
    fn fma_lowers_nested_expression() {
        // y = a * b + c  — proves the lane-splat works for nested exprs, not
        // just a single op.
        let fma = OpDef::elementwise(
            "fma",
            3,
            &[ElementKind::F32],
            input(0) * input(1) + input(2),
        );
        let a = OperandDesc::new(1, &[1 << 20], &[1], ElementKind::F32, 256);
        let key = structure_key(OpCategory::TernaryElementwise, &[a, a, a, a], ArchSku::Sm89);
        let k = generate(&fma, &key);
        assert!(k.source.contains("vo.y = ((v0.y * v1.y) + v2.y);"));
    }

    #[test]
    fn scalar_fallback_when_not_vectorizable() {
        // A transposed (strided) operand drops out of the V4 fast path.
        let strided = OperandDesc::new(2, &[1024, 1024], &[1, 1024], ElementKind::F32, 256);
        let key = structure_key(OpCategory::BinaryElementwise, &[strided, strided, strided], ArchSku::Sm89);
        let k = generate(&add_op(), &key);
        assert_eq!(k.name, "baracuda_gen_add_f32_scalar");
        assert!(k.source.contains("out[i] = (in0[i] + in1[i]);"));
    }
}
