//! The **link registry** — the `entry_point` → kernel roster the runtime binds.
//!
//! An FKC contract's `entry_point` is a *string*; to dispatch the kernel the
//! runtime must resolve that string to a callable `KernelRef` (FKC §12.6). The
//! provider owns that resolution via its `link_registry` (named in the bundle
//! front-matter as `link_registry: baracuda_link_registry`). This module emits
//! the *content* of that registry: the roster of generated entry points, each
//! tagged with the [`StructureKey`] cell it serves and its revision hash.
//!
//! The roster is emitted as a dependency-free `&[(&str, &str, u64)]`
//! (`entry_point`, structure-key token, revision hash) so the generated file
//! depends on no runtime type. At module load the sys crate resolves each symbol
//! to a `KernelRef` and registers it under its token in the binding table —
//! binding the resolved `KernelRef` is the sys crate's job; the generator owns
//! the roster.

use crate::backend::GeneratedKernel;
use crate::contract::revision_hash;
use crate::ir::OpDef;
use baracuda_kernels_types::StructureKey;

/// One generated kernel's link-registry row.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LinkEntry {
    /// Linkable symbol name — matches the contract's `entry_point`.
    pub entry_point: String,
    /// The StructureKey cell this kernel serves — matches the contract's
    /// `accept.structure_key` predicate.
    pub structure_key: String,
    /// Source-revision hash — matches the contract's `kernel_revision_hash`.
    pub revision_hash: u64,
}

/// Build the link-registry row for a generated kernel.
#[must_use]
pub fn link_entry(_op: &OpDef, key: &StructureKey, kernel: &GeneratedKernel) -> LinkEntry {
    LinkEntry {
        entry_point: kernel.name.clone(),
        structure_key: key.to_token(),
        revision_hash: revision_hash(&kernel.source),
    }
}

/// Emit the generated Rust `link_registry` source — a static roster the runtime
/// resolves to `KernelRef`s at load. Entries are sorted by `entry_point` and
/// de-duplicated for a stable, diff-friendly artifact.
#[must_use]
pub fn emit_link_registry(entries: &[LinkEntry]) -> String {
    let mut sorted: Vec<&LinkEntry> = entries.iter().collect();
    sorted.sort_by(|a, b| a.entry_point.cmp(&b.entry_point));
    sorted.dedup_by(|a, b| a.entry_point == b.entry_point);

    let mut s = String::new();
    s.push_str("// @generated by baracuda-kernelgen — do not edit.\n");
    s.push_str("//! Roster of generated kernel entry points + the StructureKey cell each\n");
    s.push_str("//! serves. The runtime resolves each `entry_point` to a `KernelRef` at module\n");
    s.push_str("//! load (FKC \u{a7}12.6) and registers it under its `structure_key` token.\n\n");
    s.push_str("/// `(entry_point, structure_key, revision_hash)` for every generated kernel.\n");
    s.push_str("pub static BARACUDA_LINK_REGISTRY: &[(&str, &str, u64)] = &[\n");
    for e in sorted {
        s.push_str(&format!(
            "    (\"{}\", \"{}\", {:#018x}),\n",
            e.entry_point, e.structure_key, e.revision_hash
        ));
    }
    s.push_str("];\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{input, OpDef};
    use crate::{generate, Cuda};
    use baracuda_kernels_types::{structure_key, ArchSku, ElementKind, OpCategory, OperandDesc};

    fn entry(name: &str) -> LinkEntry {
        let op = OpDef::elementwise(name, 2, &[ElementKind::F32], input(0) + input(1));
        let a = OperandDesc::new(2, &[128, 256], &[256, 1], ElementKind::F32, 256);
        let key = structure_key(OpCategory::BinaryElementwise, &[a, a, a], ArchSku::Sm89);
        let kernel = generate(&op, &key, &Cuda);
        link_entry(&op, &key, &kernel)
    }

    #[test]
    fn entry_mirrors_contract_fields() {
        let e = entry("add");
        assert!(e.entry_point.contains("add"));
        assert!(e.structure_key.starts_with("sk1|bin|f32|sm89|"));
        assert_ne!(e.revision_hash, 0);
    }

    #[test]
    fn registry_is_sorted_deduped_valid_rust() {
        let mut es = vec![entry("zeta"), entry("alpha"), entry("alpha")];
        // shuffle so sorting is observable.
        es.reverse();
        let src = emit_link_registry(&es);
        assert!(src.contains("pub static BARACUDA_LINK_REGISTRY: &[(&str, &str, u64)] = &["));
        // alpha sorts before zeta; the duplicate alpha collapses.
        let a = src.find("alpha").unwrap();
        let z = src.find("zeta").unwrap();
        assert!(a < z, "entries must be sorted by entry_point");
        assert_eq!(src.matches("\"baracuda_gen_alpha").count(), 1, "duplicate collapsed");
        // closes cleanly.
        assert!(src.trim_end().ends_with("];"));
    }
}
