// Generated by baracuda-cuda-emit — do not edit.
// op: matmul | cell: sk4|gem|f32|cuda:sm89|ix32|grid|r2|co/00/v4/d16/f;co/00/v4/d16/f;co/00/v4/d16/f|-|ctll/d16/f32/f32/f32/rm

extern "C" __global__ void baracuda_gen_matmul_f32_contract_tll(
    const float* __restrict__ in0,
    const float* __restrict__ in1,
    float* __restrict__ out,
    long long m,
    long long n,
    long long k)
{
    long long col = (long long)blockIdx.x * blockDim.x + threadIdx.x;
    long long step = (long long)gridDim.x * blockDim.x;
    for (; col < n; col += step) {
        float accs[8];
        #pragma unroll
        for (int mm = 0; mm < 8; ++mm) accs[mm] = 0.0f;
        for (long long kk = 0; kk < k; ++kk) {
            float w = in1[kk * n + col];
            #pragma unroll
            for (int mm = 0; mm < 8; ++mm) {
                if (mm < m) accs[mm] += in0[mm * k + kk] * w;
            }
        }
        #pragma unroll
        for (int mm = 0; mm < 8; ++mm) {
            if (mm < m) {
                float r0 = accs[mm];
                out[mm * n + col] = r0;
            }
        }
    }
}
